### ISSUE TITLE
FITS files are kept open after reading

### ISSUE THREAD

**Issue by ayshih** [sunpy/sunpy#1101]
This is probably actually an Astropy bug (or undocumented behavior), but after reading a FITS file using SunPy, it isn't possible to delete the file because it hasn't been released (on Windows).  This is part of the test `test_save()` in `test_map_factory.py`.  @ehsteve just showed me that this test passes on OS X, so this appears to be a platform-specific bug.

Using just AstroPy (0.3.2) code to demonstrate the problem:

``` python
>>> import astropy.io.fits as fits
>>> import os
>>> f = fits.open('eit_save.fits')
>>> x = f[0].data
>>> f.close() # does not actually release the file!
>>> os.remove('eit_save.fits')
ERROR: WindowsError: [Error 32] The process cannot access the file because it is
 being used by another process: 'eit_save.fits' [unknown]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
WindowsError: [Error 32] The process cannot access the file because it is being
used by another process: 'eit_save.fits'
>>> del x
>>> os.remove('eit_save.fits')
ERROR: WindowsError: [Error 32] The process cannot access the file because it is
 being used by another process: 'eit_save.fits' [unknown]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
WindowsError: [Error 32] The process cannot access the file because it is being
used by another process: 'eit_save.fits'
>>> del f[0].data
>>> os.remove('eit_save.fits') # delete succeeds
```

If a reference is created to the the HDUList data, it needs to be removed before the delete can succeed.

**Comment by ayshih** [comment]
I completely forgot about this issue, and also just noticed that there was a similar issue previously reported: #495

**Comment by ayshih** [comment]
Closing this issue because this behavior results from memory mapping in the FITS reader of PyFITS/Astropy.
