### ISSUE TITLE
MapCube animation broken

### ISSUE THREAD

**Issue by wafels** [sunpy/sunpy#1532]
Keeping the astropy normalizer (the sunpy default for the map type below) leads to a TypeError when playing a mapcube peek animation.  Also, the map is not shown. If you change the plot settings to use a native matplotlib normalizer the peek animation does not error.  The code below illustrates the issue (using sunpy/master).
```python
import sunpy.map
import matplotlib.pyplot as plt
from matplotlib.colors import PowerNorm
m = sunpy.map.Map('/Users/ireland/sunpy/data/sample_data/ssw_cutout_20121030_153001_AIA_94_.fts')
```

The following line works.  An image is shown.
```python
m.peek()
````

The code errors but keeps playing when the play button is pressed.
```python
mc = sunpy.map.Map([m,m,m], cube=True)
mc.peek()
plt.show()
```

This runs when the play button is pressed.
```python
m2 = sunpy.map.Map('/Users/ireland/sunpy/data/sample_data/ssw_cutout_20121030_153001_AIA_94_.fts')
m2.plot_settings['norm'] = PowerNorm(0.5)
mc2 = sunpy.map.Map([m2,m2,m2], cube=True)
mc2.peek()
plt.show()
```

The third map generates the same error as mc.
```python
mc3 = sunpy.map.Map([m2,m2,m], cube=True) 
mc3.peek()
plt.show()
```

**Comment by ayshih** [comment]
Error looks like:
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "c:\Anaconda\lib\lib-tk\Tkinter.py", line 1532, in __call__
    return self.func(*args)
  File "c:\Anaconda\lib\site-packages\matplotlib\backends\backend_tkagg.py", line 416, in button_release_event
    FigureCanvasBase.button_release_event(self, x, y, num, guiEvent=event)
  File "c:\Anaconda\lib\site-packages\matplotlib\backend_bases.py", line 1910, in button_release_event
    self.callbacks.process(s, event)
  File "c:\Anaconda\lib\site-packages\matplotlib\cbook.py", line 540, in process
    proxy(*args, **kwargs)
  File "c:\Anaconda\lib\site-packages\matplotlib\cbook.py", line 415, in __call__
    return mtd(*args, **kwargs)
  File "c:\users\albert\onedrive\code\sunpy\sunpy\visualization\imageanimator.py", line 87, in _release
    func(event, *self.clicked_args[cid])
  File "c:\users\albert\onedrive\code\sunpy\sunpy\visualization\imageanimator.py", line 404, in _click_slider_button
    self._set_active_slider(slider.slider_ind)
  File "c:\users\albert\onedrive\code\sunpy\sunpy\visualization\imageanimator.py", line 288, in _set_active_slider
    self._dehighlight_slider(self.active_slider)
  File "c:\users\albert\onedrive\code\sunpy\sunpy\visualization\imageanimator.py", line 300, in _dehighlight_slider
    self.fig.canvas.draw()
  File "c:\Anaconda\lib\site-packages\matplotlib\backends\backend_tkagg.py", line 349, in draw
    FigureCanvasAgg.draw(self)
  File "c:\Anaconda\lib\site-packages\matplotlib\backends\backend_agg.py", line 469, in draw
    self.figure.draw(self.renderer)
  File "c:\Anaconda\lib\site-packages\matplotlib\artist.py", line 59, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "c:\Anaconda\lib\site-packages\matplotlib\figure.py", line 1085, in draw
    func(*args)
  File "c:\Anaconda\lib\site-packages\matplotlib\artist.py", line 59, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "c:\Anaconda\lib\site-packages\matplotlib\axes\_base.py", line 2110, in draw
    a.draw(renderer)
  File "c:\Anaconda\lib\site-packages\matplotlib\artist.py", line 59, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "c:\Anaconda\lib\site-packages\matplotlib\image.py", line 373, in draw
    im = self.make_image(renderer.get_image_magnification())
  File "c:\Anaconda\lib\site-packages\matplotlib\image.py", line 597, in make_image
    transformed_viewLim)
  File "c:\Anaconda\lib\site-packages\matplotlib\image.py", line 212, in _get_unsampled_image
    x = self.to_rgba(self._A, bytes=False)
  File "c:\Anaconda\lib\site-packages\matplotlib\cm.py", line 262, in to_rgba
    x = self.norm(x)
  File "c:\Anaconda\lib\site-packages\astropy\visualization\mpl_normalize.py", line 71, in __call__
    np.subtract(values, self.vmin, out=values)
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'
```
`self.vmin` is `None`?  Perhaps there is some bug with Astropy's determination of the minimum value in the array?

**Comment by ayshih** [comment]
The issue is related to the `im.set_norm()` calls in `mapcube.py` and `mapcubeanimator.py`, and one should actually pass in a `deepcopy()` of the normalizer.  It seems that `autoscale_None()` is not getting called automatically for Astropy's derived normalizers, but calling it explicitly doesn't appear to be a total fix because something seems to break with the desired `stretch`.

**Comment by ayshih** [comment]
PR to our repo: #1542
PR to Astropy's repo: https://github.com/astropy/astropy/pull/4117

**Comment by Cadair** [comment]
nice, silly astropy bugs...

**Comment by wafels** [comment]
Tried with one of my cubes, and thefix works

Also works for PowerNorm from matplotlib.colors too.

**Comment by Cadair** [comment]
@ayshih can you back port this to the 0.6 branch?

**Comment by ayshih** [comment]
PR #1543 for backport, I'll let someone else do it
