### ISSUE TITLE
Naming conflict with xml.py in sunpy.util

### ISSUE THREAD

**Issue by sudk1896** [sunpy/sunpy#1820]
I was trying out something with `scraper``in``sunpy.util`` . When I tried running it, I got the following error message.

```

Traceback (most recent call last):
  File "/home/sudarshan/sample.py", line 37, in <module>
    from sunpy.net.vso.attrs import Time,Instrument, Level,Source,Detector,Physobs,Wavelength
  File "/home/sudarshan/sunpy/sunpy/net/__init__.py", line 5, in <module>
    from sunpy.net.dataretriever import Fido
  File "/home/sudarshan/sunpy/sunpy/net/dataretriever/__init__.py", line 50, in <module>
    from .client import QueryResponseBlock, QueryResponse, GenericClient
  File "/home/sudarshan/sunpy/sunpy/net/dataretriever/client.py", line 16, in <module>
    from ..vso.attrs import Time, Wavelength
  File "/home/sudarshan/sunpy/sunpy/net/vso/__init__.py", line 4, in <module>
    from sunpy.net.vso.vso import VSOClient, InteractiveVSOClient
  File "/home/sudarshan/sunpy/sunpy/net/vso/vso.py", line 24, in <module>
    from suds import client, TypeNotFound
  File "/usr/local/lib/python2.7/dist-packages/suds/__init__.py", line 154, in <module>
    import client
  File "/usr/local/lib/python2.7/dist-packages/suds/client.py", line 26, in <module>
    from suds.reader import DefinitionsReader
  File "/usr/local/lib/python2.7/dist-packages/suds/reader.py", line 22, in <module>
    from suds.sax.parser import Parser
  File "/usr/local/lib/python2.7/dist-packages/suds/sax/parser.py", line 37, in <module>
    from xml.sax import make_parser, InputSource, ContentHandler
  File "/home/sudarshan/sunpy/sunpy/util/xml.py", line 5, in <module>
    from xml.dom.minidom import parseString #pylint: disable=E0611,F0401
ImportError: No module named dom.minidom
```

A few google searches later I found it is a popular mistake/issue as said [here](http://stackoverflow.com/questions/29273799/importerror-no-module-named-dom). Anybody else ever face this issue, if so what is the workaround ?

I resolved the issue after renaming xml.py to something else.

**Comment by Cadair** [comment]
I *think* putting `from __future__ import absolute_import` at the top should fix it.

**Comment by Cadair** [comment]
ok xml.py that is.

**Comment by sudk1896** [comment]
I already have that, the issue still arises though.

**Comment by Cadair** [comment]
huh, interesting, I will look.

**Comment by ayshih** [comment]
Even when using `absolute_import` on Python 2.7, the choice of working directory can cause quirks, and I suspect this error was encountered when running code while in `sunpy/util/`.  You can reproduce this Python 2.7 behavior by calling `import sunpy.util.xml` when in `sunpy/util/` versus when in a different directory.

Of course, we could rename `xml.py` to avoid the name collision altogether, but it generally shouldn't be an issue.
