### ISSUE TITLE
Port the figure tests to Python 3

### ISSUE THREAD

**Issue by wafels** [sunpy/sunpy#1873]
Using Python 3.5 and trying to write a new figure hash table, I got this error.  Googling the TypeError at the end shows that this is a Python 2/3 issue.

http://stackoverflow.com/questions/33054527/python-3-5-typeerror-a-bytes-like-object-is-required-not-str

```
All test files for figure hashes can be found in /tmp/tmp_xhdqdu9_figures
Traceback (most recent call last):
  File "/home/ireland/anaconda3/bin/py.test", line 6, in <module>
    sys.exit(py.test.main())
  File "/home/ireland/anaconda3/lib/python3.5/site-packages/_pytest/config.py", line 49, in main
    return config.hook.pytest_cmdline_main(config=config)
  File "/home/ireland/anaconda3/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 724, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/home/ireland/anaconda3/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 338, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/ireland/anaconda3/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 333, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/home/ireland/anaconda3/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 596, in execute
    res = hook_impl.function(*args)
  File "/home/ireland/anaconda3/lib/python3.5/site-packages/_pytest/main.py", line 119, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/home/ireland/anaconda3/lib/python3.5/site-packages/_pytest/main.py", line 115, in wrap_session
    config._ensure_unconfigure()
  File "/home/ireland/anaconda3/lib/python3.5/site-packages/_pytest/config.py", line 844, in _ensure_unconfigure
    self.hook.pytest_unconfigure(config=self)
  File "/home/ireland/anaconda3/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 724, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/home/ireland/anaconda3/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 338, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/ireland/anaconda3/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 333, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/home/ireland/anaconda3/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 596, in execute
    res = hook_impl.function(*args)
  File "/home/ireland/projects/sunpy/sunpy/sunpy/conftest.py", line 70, in pytest_unconfigure
    json.dump(hash.hash_library, outfile, sort_keys=True, indent=4, separators=(',', ': '))
  File "/home/ireland/anaconda3/lib/python3.5/json/__init__.py", line 179, in dump
    fp.write(chunk)
TypeError: a bytes-like object is required, not 'str'
```

**Comment by ayshih** [comment]
For posterity, this bug turned out to be really easy to fix.  For some reason, I opened the output file as binary when using  `json.dump`, which always writes strings.  This is a problem in Python 3.5 because you're no longer allowed to write strings to binary files, so the output file just needs to be opened as text (as should have always been the case).
