### ISSUE TITLE
Sample class sunpy.net.jsoc. Doesn't seem available in 0.8 and connection refused problem

### ISSUE THREAD

**Issue by amunozj** [sunpy/sunpy#2279]
Hi Guys!

I was playing with the jsoc client and it I cannot find the Sampling cadence anymore (it did on 0.7).  I'm doing something like this

```
from sunpy.net import jsoc

response = client.search(jsoc.attrs.Time(date_start, date_end), jsoc.attrs.Series('hmi.M_720s'), jsoc.attrs.Notify('email'), jsoc.Sample(2*u.hour))
```

I'm using 'jsoc.Sample(2*u.hour)' so that I get the images every two hours.  

the page for Sample class sunpy.net.jsoc. Appears as not existing yet.

Thanks for all your hard work!

Andrés

**Comment by nitinkgp23** [comment]
Hello,
the new JSOCClient will bring this back. For now, you can use the vso Sample attr instead:

```
>>> from sunpy.net import jsoc, attrs
>>> response = client.search(attrs.jsoc.Time(date_start, date_end), attrs.jsoc.Series('hmi.M_720s'), 
                                               attrs.jsoc.Notify('email'), attrs.vso.Sample(2*u.hour))
```

**Comment by amunozj** [comment]
Thank you Nitin.  That helped, can abuse your kindness and ask you a related question?  I'm running into a problem where I'm downloading multiple sequences of images and I'm running into a connection problem.   Here is reduced form of my code:

```
while (not it.finished) and (count < 50):
    date_s = datetime.datetime.strftime(dateStr,'%Y-%m-%dT%H:%M:00')
    date_e = datetime.datetime.strftime(dateEnd,'%Y-%m-%dT%H:%M:00')

    client = jsoc.JSOCClient()
    response = client.search(jsoc.attrs.Time(date_s, date_e),jsoc.attrs.Series('hmi.M_720s'), jsoc.attrs.Notify('amunozj@boulder.swri.edu'), attrs.vso.Sample(2*u.hour))
    print(response)

    res = client.fetch(response, path = newpath)
```

It basically goes to a bunch of arbitrary dates and grabs all magnetograms in a 10 hour sequence every two hours.   The problem is that when I run it I get the following error:

```
Traceback (most recent call last):
  File "/home/amunozj/anaconda3/lib/python3.6/site-packages/requests/packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/home/amunozj/anaconda3/lib/python3.6/site-packages/requests/packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/home/amunozj/anaconda3/lib/python3.6/site-packages/requests/packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/amunozj/anaconda3/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/amunozj/anaconda3/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 356, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/amunozj/anaconda3/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/amunozj/anaconda3/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/amunozj/anaconda3/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/amunozj/anaconda3/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/home/amunozj/anaconda3/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/home/amunozj/anaconda3/lib/python3.6/site-packages/requests/packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/home/amunozj/anaconda3/lib/python3.6/site-packages/requests/packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
requests.packages.urllib3.exceptions.NewConnectionError: <requests.packages.urllib3.connection.HTTPConnection object at 0x7f0a50011748>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/amunozj/anaconda3/lib/python3.6/site-packages/requests/adapters.py", line 438, in send
    timeout=timeout
  File "/home/amunozj/anaconda3/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 649, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/amunozj/anaconda3/lib/python3.6/site-packages/requests/packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
requests.packages.urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='jsoc.stanford.edu', port=80): Max retries exceeded with url: /cgi-bin/ajax/jsoc_info?ds=hmi.M_720s%5B2014.10.24_17%3A42%3A00_TAI-2014.10.25_01%3A42%3A00_TAI%407200.0s%5D&op=rs_list&key=DATE%2CTELESCOP%2CINSTRUME%2CT_OBS%2CWAVELNTH%2CWAVEUNIT&seg=%2A%2ANONE%2A%2A&link=%2A%2ANONE%2A%2A (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f0a50011748>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hmi_download_fl.py", line 51, in <module>
    response = client.search(jsoc.attrs.Time(date_s, date_e),jsoc.attrs.Series('hmi.M_720s'), jsoc.attrs.Notify('amunozj@boulder.swri.edu'), attrs.vso.Sample(2*u.hour))
  File "/home/amunozj/anaconda3/lib/python3.6/site-packages/sunpy/net/jsoc/jsoc.py", line 218, in search
    return_results.append(self._lookup_records(iargs))
  File "/home/amunozj/anaconda3/lib/python3.6/site-packages/sunpy/net/jsoc/jsoc.py", line 612, in _lookup_records
    r = requests.get(JSOC_INFO_URL, params=postthis)
  File "/home/amunozj/anaconda3/lib/python3.6/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/amunozj/anaconda3/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/amunozj/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 518, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/amunozj/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 639, in send
    r = adapter.send(request, **kwargs)
  File "/home/amunozj/anaconda3/lib/python3.6/site-packages/requests/adapters.py", line 502, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='jsoc.stanford.edu', port=80): Max retries exceeded with url: /cgi-bin/ajax/jsoc_info?ds=hmi.M_720s%5B2014.10.24_17%3A42%3A00_TAI-2014.10.25_01%3A42%3A00_TAI%407200.0s%5D&op=rs_list&key=DATE%2CTELESCOP%2CINSTRUME%2CT_OBS%2CWAVELNTH%2CWAVEUNIT&seg=%2A%2ANONE%2A%2A&link=%2A%2ANONE%2A%2A (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f0a50011748>: Failed to establish a new connection: [Errno 111] Connection refused',))

```

Seems like by trying to download several sequences jsoc is shutting me out.  Is there a way to make the number of attempts to make the connection larger, or some time delay between attempts?

**Comment by amunozj** [comment]
Ok, I fixed it by adding:

file_paths = res.wait()

thank you!
