### ISSUE TITLE
JSOC Client errors with `Protocol("as-is")`

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#2631]
```python
query = a.jsoc.Time("2014-12-18T18:00:00", "2014-12-18T18:00:00") & a.jsoc.Series("hmi.m_720s") & a.jsoc.Notify(email)
res = Fido.search(query)
files = Fido.fetch(res)
```
```
Traceback (most recent call last):
  File "plot_jsoc_map_asis_sunpy", line 20, in <module>
    files = Fido.fetch(res)
  File "/home/stuart/Git/sunpy/sunpy/net/fido_factory.py", line 362, in fetch
    reslist.append(block.client.fetch(block, **kwargs))
  File "/home/stuart/Git/sunpy/sunpy/net/jsoc/jsoc.py", line 547, in fetch
    progress=progress, results=r)
  File "/home/stuart/Git/sunpy/sunpy/net/jsoc/jsoc.py", line 651, in get_request
    url_dir = request.request_url + '/'
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

**Comment by sashank27** [comment]
The http query created would be: `http://jsoc.stanford.edu/cgi-bin/ajax/jsoc_fetch?op=exp_request&format=json&ds=hmi.m_720s%5B2014.12.18_18%3A00%3A35_TAI-2014.12.18_18%3A00%3A35_TAI%5D&notify=<email>&method=url_quick&protocol=as-is&filenamefmt=hmi.m_720s.%7BT_REC%3AA%7D.%7BCAMERA%7D.%7Bsegment%7D&requestor=jsoc`

The results clearly has `dir=''`. By definition of [`request_data`](https://github.com/sunpy/drms/blob/a9de2819d9e0aad715894cc4de889ba4b3a7fdad/drms/client.py#L341) the `request_data` is None if `self.dir` is None. Also, from the definition of [`dir`](https://github.com/sunpy/drms/blob/a9de2819d9e0aad715894cc4de889ba4b3a7fdad/drms/client.py#L295) it would be None.

I'm not sure how can I fix it, but this is what I found.
