### ISSUE TITLE
Scraper errors when directory in pattern doesn't exist

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#2684]
i.e. when you have a pattern like `http://mywebsite/%Y/%Y%m%d` if you ask for a year that doesn't exist it will fail because it will try and get the directory.

**Comment by Brhstone** [comment]
```
Traceback (most recent call last):
  File "/Users/brst3037/opt/anaconda36/envs/sunpy/lib/python3.6/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "/Users/brst3037/code/sunpy/sunpy/net/fido_factory.py", line 326, in search
    return UnifiedResponse(query_walker.create(query, self))
  File "/Users/brst3037/code/sunpy/sunpy/net/attr.py", line 240, in create
    return self.createmm(self, *args, **kwargs)
  File "/Users/brst3037/code/sunpy/sunpy/util/multimethod.py", line 120, in __call__
    return cached(*args, **kwargs)
  File "/Users/brst3037/code/sunpy/sunpy/net/fido_factory.py", line 260, in _create_and
    return [factory._make_query_to_client(*query.attrs)]
  File "/Users/brst3037/code/sunpy/sunpy/net/fido_factory.py", line 418, in _make_query_to_client
    return tmpclient.search(*query), tmpclient
  File "/Users/brst3037/code/sunpy/sunpy/net/dataretriever/client.py", line 324, in search
    self.map_.get('TimeRange'), **kwergs)
  File "/Users/brst3037/code/sunpy/sunpy/net/dataretriever/sources/eve.py", line 170, in _get_url_for_timerange
    return eve.filelist(timerange)
  File "/Users/brst3037/code/sunpy/sunpy/util/scraper.py", line 226, in filelist
    opn = urlopen(directory)
  File "/Users/brst3037/opt/anaconda36/envs/sunpy/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/brst3037/opt/anaconda36/envs/sunpy/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/Users/brst3037/opt/anaconda36/envs/sunpy/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Users/brst3037/opt/anaconda36/envs/sunpy/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/Users/brst3037/opt/anaconda36/envs/sunpy/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/Users/brst3037/opt/anaconda36/envs/sunpy/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by samaloney** [comment]
What's the expected fix, return a second list of failed files or include the failed ones in the currently returned list?

**Comment by nabobalis** [comment]
@Cadair your thoughts?

**Comment by Cadair** [comment]
I would need to double check how the scraper handles it, but I think the answer is just to return an empty list because it dosen't find any files.

**Comment by Cadair** [comment]
looks like @Brhstone has a patch here: https://github.com/Brhstone/sunpy/commit/a62eec76d527a91101dc35a01284148122a47aec#diff-587d81658a6b5d15d91bb0e994a9f63b

**Comment by samaloney** [comment]
How would you then know what data wasn't found, I was going to suggest just return the http status error code instead of the url?

**Comment by Cadair** [comment]
The scraper only returns results for files it can find on the remote host based on a URL pattern. If you want to know all possible urls based on the pattern you will probably have to generate them yourself.

**Comment by samaloney** [comment]
Ok. That codes not in a pull request so what the procedure, clone that repo and make  PR for that one change?

**Comment by Cadair** [comment]
Ask @Brhstone nicely to PR the fix separately :laughing: 

Failing that I think you will have to just remake the patch because there isn't really a commit you can cherry-pick

**Comment by dpshelio** [comment]
The way the scraper works I would expect to only get a list with the available files. So, if my query ranges 3 days, but there's no data in the middle one, the list of files should only show the ones on the first and last day. Non-error should be shown as the scraper doesn't have a concept of what's the expected cadence (though it could be added and then show some stats or warnings). The only errors I expect is when the user doesn't have a working connection, the server is not available or when you don't have permissions to access to these directories (as it could be an ftp directory that needs the appropriate credentials).

Since we don't know whether the server is supposed to have that data or not... some instruments produce data constantly from space, but ground-based telescopes may have not have observations because it was raining... Or they are not updating the data in the server every day. So, showing the 404 error message is not more helpful to the user than just giving a blank list. It's up to the user to check again later or investigate why there's no data that day.

**Comment by Brhstone** [comment]
@Cadair, thanks for the reminder. ;)

I should be able to make that PR tomorrow.
