### ISSUE TITLE
Slicing a JSOC UnifiedResponse object causes Fido.fetch to fail

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#2781]
```python
tstart = '2011/06/07 06:32:45'
tend = '2011/06/07 06:33:15'                                                                                                                                                                 

res = Fido.search(a.jsoc.Time(tstart, tend), a.jsoc.Series('hmi.M_45s'))

Fido.fetch(res[0,0])
```
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-488027c4a327> in <module>
----> 1 Fido.fetch(res[0,0])

~/Git/sunpy/sunpy/net/fido_factory.py in fetch(self, *query_results, **kwargs)
    360         for query_result in query_results:
    361             for block in query_result.responses:
--> 362                 reslist.append(block.client.fetch(block, **kwargs))
    363 
    364         results = DownloadResponse(reslist)

~/Git/sunpy/sunpy/net/jsoc/jsoc.py in fetch(self, jsoc_response, path, overwrite, progress, max_conn, downloader, sleep)
    532 
    533         # Make staging request to JSOC
--> 534         responses = self.request_data(jsoc_response)
    535         # Make response iterable
    536         if not isiterable(responses):

~/Git/sunpy/sunpy/net/jsoc/jsoc.py in request_data(self, jsoc_response, **kwargs)
    428         requests = []
    429         self.query_args = jsoc_response.query_args
--> 430         for block in jsoc_response.query_args:
    431 
    432             ds = self._make_recordset(**block)

TypeError: 'NoneType' object is not iterable
```

**Comment by eamanu** [comment]
Hi, 

I cannot reproduce, exactly, the bug. 

I try this, but the error is different, we are talking about the same problem?

```
>>> import sunpy.map
>>> from sunpy.net import Fido
>>> from sunpy.net import jsoc
>>> tstart = '2011/06/07 06:32:45'
>>> tend = '2011/06/07 06:33:15'
>>> res = Fido.search(a.jsoc.Time(tstart, tend), a.jsoc.Series('hmi.M_45s'))
>>> Fido.fetch(res[0,0])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/eamanu/dev/sunpy/sunpy/net/fido_factory.py", line 362, in fetch
    reslist.append(block.client.fetch(block, **kwargs))
  File "/home/eamanu/dev/sunpy/sunpy/net/jsoc/jsoc.py", line 534, in fetch
    responses = self.request_data(jsoc_response)
  File "/home/eamanu/dev/sunpy/sunpy/net/jsoc/jsoc.py", line 430, in request_data
    for block in jsoc_response.query_args:
TypeError: 'NoneType' object is not iterable

```

**Comment by nabobalis** [comment]
Hi @eamanu, the error is the same. The difference is how IPython displays the traceback compared to the normal Python interpreter.

**Comment by eamanu** [comment]
Ok thanks!

**Comment by yashrsharma44** [comment]
Can I work on this issue?

**Comment by nabobalis** [comment]
Sure, but we do have an open pull request: https://github.com/sunpy/sunpy/pull/2796 on it.
