### ISSUE TITLE
Pip installing sunpy dev fails

### ISSUE THREAD

**Issue by bsipocz** [sunpy/sunpy#2905]
With `ci-helpers` I run into this issue for both travis/linux and appveyor:

Please have a look and open a PR in `ci-helpers` with the suggested fix for the case of `SUNPY_VERSION='dev'`

```
+++++python -m pip install git+https://github.com/sunpy/sunpy.git#egg=sunpy --upgrade --no-deps
Collecting sunpy from git+https://github.com/sunpy/sunpy.git#egg=sunpy
  Cloning https://github.com/sunpy/sunpy.git to /tmp/pip-install-uowizwdl/sunpy
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  Complete output from command /home/travis/miniconda/envs/test/bin/python /home/travis/miniconda/envs/test/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp6h0521mp:
  Traceback (most recent call last):
    File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>
      main()
    File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 197, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 54, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-3jro2te9/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 115, in get_requires_for_build_wheel
      return _get_build_requires(config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-3jro2te9/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 101, in _get_build_requires
      _run_setup()
    File "/tmp/pip-build-env-3jro2te9/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 85, in _run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 46, in <module>
      import ah_bootstrap  # noqa
  ModuleNotFoundError: No module named 'ah_bootstrap'
```

**Comment by nabobalis** [comment]
We have a fix for it here: https://github.com/sunpy/sunpy/pull/2906
