### ISSUE TITLE
sunpy.map fails with ADAPT/GONG synoptic maps

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#2924]
```python
import sunpy.map
m = sunpy.map.Map('adapt_maps/adapt41311_02e012_201902041400_i00005600n0.fts')
print(m)
```
where the map is from ftp://gong.nso.edu/adapt/maps/gong/2019 results in
```python
/Users/dstansby/miniconda3/lib/python3.7/site-packages/sunpy/map/mapbase.py:193: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  data = data[new_2d_slice]
/Users/dstansby/miniconda3/lib/python3.7/site-packages/sunpy/map/mapbase.py:362: Warning: This file contains more than 2 dimensions. Only the first two dimensions will be used. The truncated data will not be saved in a new file.
  The number of pixels in the array of the map.
/Users/dstansby/miniconda3/lib/python3.7/site-packages/sunpy/map/mapbase.py:258: Warning: Missing metadata for observation time: setting observation time to current time
  meas=self.measurement, wave=self.wavelength, date=self.date,
/Users/dstansby/miniconda3/lib/python3.7/site-packages/sunpy/map/mapbase.py:673: Warning: Missing metadata for heliographic latitude: assuming Earth-based observer
  return SkyCoord(lat=self.heliographic_latitude,
/Users/dstansby/miniconda3/lib/python3.7/site-packages/sunpy/map/mapbase.py:674: Warning: Missing metadata for heliographic longitude: assuming longitude of 0 degrees
  lon=self.heliographic_longitude,
/Users/dstansby/miniconda3/lib/python3.7/site-packages/sunpy/map/mapbase.py:675: Warning: Missing metadata for Sun-spacecraft separation: assuming Sun-Earth distance
  radius=self.dsun,
Traceback (most recent call last):
  File "adapt_sunpy_map.py", line 3, in <module>
    print(m)
  File "/Users/dstansby/miniconda3/lib/python3.7/site-packages/sunpy/map/mapbase.py", line 262, in __repr__
    coord=self.coordinate_frame,
  File "/Users/dstansby/miniconda3/lib/python3.7/site-packages/sunpy/map/mapbase.py", line 320, in coordinate_frame
    return astropy.wcs.utils.wcs_to_celestial_frame(self.wcs)
  File "/Users/dstansby/miniconda3/lib/python3.7/site-packages/astropy/wcs/utils.py", line 212, in wcs_to_celestial_frame
    raise ValueError("Could not determine celestial frame corresponding to "
ValueError: Could not determine celestial frame corresponding to the specified WCS object
```
### System Details

  - SunPy Version: 0.9.6
  - Python Version: 3.7.2
  - OS information: MacOS

**Comment by Cadair** [comment]
Can you provide a file or the full header please? :angel:

**Comment by Cadair** [comment]
So the relevant bit of the header is here:

```
WCSNAME = 'Heliocentric-cart'                                                   
CTYPE1  = 'Long    '           / Coordinate axis label                          
CTYPE2  = 'Lat     '           / Coordinate axis label                          
CRPIX1  =                180.5 / Current X position for center                  
CRPIX2  =                 90.5 / Current Y position for center                  
CUNIT1  = 'deg     '           / X axis units                                   
CUNIT2  = 'deg     '           / Y axis units                                   
CDELT1  =                   1. / X resolution [deg/pxl]                         
CDELT2  =                   1. / Y resolution [deg/pxl]                         
CRVAL1  =                 113. / Reference pixel value                          
CRVAL2  =                   0. / Reference pixel value                          
```
This is not even vaguely a standard compliant file, so I am not surprised we can't parse it. 

I think you are doing an excellent job of making us question what the scope of `Map` is, which really is a long overdue thing. I am not sure what's the best way to have this discussion but it's closely tied to #2847

**Comment by dstansby** [comment]
I think this is covered by the doc change I made a while ago that tells users how to fix a header before loading the map, so closing.
