### ISSUE TITLE
VSOClient should fail to initilize if it can't read the WSDL

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#2981]
Currently what happens is this:

```
/home/stuart/Git/sunpy/sunpy/net/vso/vso.py:93: UserWarning: Connection failed with error <urlopen error [Errno -3] Temporary failure in name resolution>. 
 Retrying with different url and port.
  "Connection failed with error {}. \n Retrying with different url and port.".format(e))
Traceback (most recent call last):
  File "test_download.py", line 14, in <module>
    a.Wavelength(171*u.angstrom) | a.Wavelength(94*u.angstrom))
  File "/home/stuart/Git/sunpy/sunpy/net/fido_factory.py", line 297, in search
    return UnifiedResponse(query_walker.create(query, self))
  File "/home/stuart/Git/sunpy/sunpy/net/attr.py", line 411, in create
    return self.createmm(self, *args, **kwargs)
  File "/home/stuart/Git/sunpy/sunpy/util/multimethod.py", line 120, in __call__
    return fun(*args, **kwargs)
  File "/home/stuart/Git/sunpy/sunpy/net/fido_factory.py", line 238, in _create_or
    qblocks.extend(walker.create(attr.and_(attrblock), factory))
  File "/home/stuart/Git/sunpy/sunpy/net/attr.py", line 411, in create
    return self.createmm(self, *args, **kwargs)
  File "/home/stuart/Git/sunpy/sunpy/util/multimethod.py", line 120, in __call__
    return fun(*args, **kwargs)
  File "/home/stuart/Git/sunpy/sunpy/net/fido_factory.py", line 231, in _create_and
    return [factory._make_query_to_client(*query.attrs)]
  File "/home/stuart/Git/sunpy/sunpy/net/fido_factory.py", line 431, in _make_query_to_client
    return tmpclient.search(*query), tmpclient
  File "/home/stuart/Git/sunpy/sunpy/net/vso/vso.py", line 303, in search
    QueryRequest = self.api.get_type('VSO:QueryRequest')
AttributeError: 'NoneType' object has no attribute 'get_type'


```

**Comment by Cadair** [comment]
You can reproduce this by creating `VSOClient()` object without an internet connection.

**Comment by nabobalis** [comment]
I wonder how many clients also error like that.
