### ISSUE TITLE
Panning/zooming a plotted Map broken with (unreleased) Matplotlib 3.1.0

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#3028]
### Description
Zooming or panning a plotted map is broken with the currently master branch of Maptlotlib, that should shortly be released as version `3.1.0`. I am aware that this is not the best bug report, but I thought I'd leave it anyway as a placeholder for fixing at some point.

**This might  be an upstream Maptlotlib issue.**

### Steps to Reproduce

1. Install Matplotlib master branch
2. Plot a `Map`
3. Try to zoom/pan

Error message is:
```python
Traceback (most recent call last):
  File "/Users/dstansby/miniconda3/lib/python3.7/site-packages/numpy/lib/shape_base.py", line 743, in array_split
    Ntotal = ary.shape[axis]
AttributeError: 'NoneType' object has no attribute 'shape'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dstansby/github/matplotlib/lib/matplotlib/cbook/__init__.py", line 216, in process
    func(*args, **kwargs)
  File "/Users/dstansby/github/matplotlib/lib/matplotlib/backend_bases.py", line 2830, in press_zoom
    if (x is not None and y is not None and a.in_axes(event) and
  File "/Users/dstansby/github/matplotlib/lib/matplotlib/axes/_base.py", line 2126, in in_axes
    return self.patch.contains(mouseevent)[0]
  File "/Users/dstansby/github/matplotlib/lib/matplotlib/patches.py", line 144, in contains
    Path, np.split(vertices, idxs), np.split(codes, idxs))), {}
  File "/Users/dstansby/miniconda3/lib/python3.7/site-packages/numpy/lib/shape_base.py", line 850, in split
    res = array_split(ary, indices_or_sections, axis)
  File "/Users/dstansby/miniconda3/lib/python3.7/site-packages/numpy/lib/shape_base.py", line 745, in array_split
    Ntotal = len(ary)
TypeError: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/Users/dstansby/miniconda3/lib/python3.7/site-packages/numpy/lib/shape_base.py", line 743, in array_split
    Ntotal = ary.shape[axis]
AttributeError: 'NoneType' object has no attribute 'shape'
```

### System Details

  - SunPy Version: master branch
  - Python Version: 3.7
  - OS information: MacOS

**Comment by Cadair** [comment]
I wonder if this is actually an astropy / wcsaxes issue (with mpl). I will try and investigate.

**Comment by dstansby** [comment]
Yeah, I can reproduce with just `astropy`: https://github.com/astropy/astropy/issues/8545

**Comment by dstansby** [comment]
This is fixed upstream now.
