### ISSUE TITLE
database guide doctests fail with database locked

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#3071]
#3069 skips all the doctests in `docs/guide/acquiring_data/database.rst` due to the following error, this needs investigating and fixing.

```
_________________________________________________________________ [doctest] docs/guide/acquiring_data/database.rst _________________________________________________________________
162 Using the function `len` on a :class:`Database` object returns the
163 number of saved database entries. To get the first entry of the database,
164 ``database[0]`` is used (the ID number of the entries does not matter,
165 ``database[0]`` always returns the oldest saved entry of the database). If
166 the database is empty, this expression raises an :exc:`IndexError`.
167 In section 3, more advanced formats of the slicing syntax are introduced.
168 
169     >>> import sunpy.data.sample  # doctest: +REMOTE_DATA
170     >>> database.add_from_file(sunpy.data.sample.AIA_171_IMAGE)  # doctest: +REMOTE_DATA
171     >>> len(database)  # doctest: +REMOTE_DATA
UNEXPECTED EXCEPTION: OperationalError('(sqlite3.OperationalError) database is locked')
Traceback (most recent call last):

  File "/home/vsts/work/1/s/.tox/py37-online/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context

  File "/home/vsts/work/1/s/.tox/py37-online/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)

sqlite3.OperationalError: database is locked


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "/opt/hostedtoolcache/Python/3.7.2/x64/lib/python3.7/doctest.py", line 1329, in __run
    compileflags, 1), test.globs)

  File "<doctest database.rst[4]>", line 1, in <module>

  File "/home/vsts/work/1/s/.tox/py37-online/lib/python3.7/site-packages/sunpy/database/database.py", line 1091, in __len__
    return self.session.query(tables.DatabaseEntry).count()

  File "/home/vsts/work/1/s/.tox/py37-online/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3561, in count
    return self.from_self(col).scalar()

  File "/home/vsts/work/1/s/.tox/py37-online/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3305, in scalar
    ret = self.one()

  File "/home/vsts/work/1/s/.tox/py37-online/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3275, in one
    ret = self.one_or_none()

  File "/home/vsts/work/1/s/.tox/py37-online/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3244, in one_or_none
    ret = list(self)

  File "/home/vsts/work/1/s/.tox/py37-online/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3316, in __iter__
    self.session._autoflush()

  File "/home/vsts/work/1/s/.tox/py37-online/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1587, in _autoflush
    util.raise_from_cause(e)

  File "/home/vsts/work/1/s/.tox/py37-online/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)

  File "/home/vsts/work/1/s/.tox/py37-online/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 129, in reraise
    raise value

  File "/home/vsts/work/1/s/.tox/py37-online/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1576, in _autoflush
    self.flush()

  File "/home/vsts/work/1/s/.tox/py37-online/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2451, in flush
    self._flush(objects)

  File "/home/vsts/work/1/s/.tox/py37-online/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2589, in _flush
    transaction.rollback(_capture_exception=True)

  File "/home/vsts/work/1/s/.tox/py37-online/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)

  File "/home/vsts/work/1/s/.tox/py37-online/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 129, in reraise
    raise value

  File "/home/vsts/work/1/s/.tox/py37-online/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2549, in _flush
    flush_context.execute()

  File "/home/vsts/work/1/s/.tox/py37-online/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)

  File "/home/vsts/work/1/s/.tox/py37-online/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
    uow,

  File "/home/vsts/work/1/s/.tox/py37-online/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    insert,

  File "/home/vsts/work/1/s/.tox/py37-online/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 1120, in _emit_insert_statements
    statement, params

  File "/home/vsts/work/1/s/.tox/py37-online/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)

  File "/home/vsts/work/1/s/.tox/py37-online/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)

  File "/home/vsts/work/1/s/.tox/py37-online/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,

  File "/home/vsts/work/1/s/.tox/py37-online/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context

  File "/home/vsts/work/1/s/.tox/py37-online/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)

  File "/home/vsts/work/1/s/.tox/py37-online/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)

  File "/home/vsts/work/1/s/.tox/py37-online/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 128, in reraise
    raise value.with_traceback(tb)

  File "/home/vsts/work/1/s/.tox/py37-online/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context

  File "/home/vsts/work/1/s/.tox/py37-online/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)

sqlalchemy.exc.OperationalError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(sqlite3.OperationalError) database is locked
[SQL: INSERT INTO data (source, provider, physobs, fileid, observation_time_start, observation_time_end, instrument, size, wavemin, wavemax, hdu_index, path, download_time, starred) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: (None, None, None, None, '2011-06-07 06:33:02.770000', None, 'AIA_3', None, 17.1, 17.1, 0, '/home/vsts/.local/share/sunpy/AIA20110607_063302_0171_lowres.fits', None, 0)]
(Background on this error at: http://sqlalche.me/e/e3q8)
```

**Comment by nabobalis** [comment]
The future of database is pretty much on life support so there is no point in fixing issues for that.
