### ISSUE TITLE
parfive fails to download if some clients return no results

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#3292]
Take the following example:

```python
import asyncio

import astropy.units as u
from sunpy.net import Fido
from sunpy.net import attrs as a

import parfive

stereo = (a.Detector('STEREO_B') &
          a.Instrument('EUVI') &
          a.Time('2011-01-01', '2011-01-01T00:10:00'))

aia = (a.Instrument('AIA') &
       a.Sample(24 * u.hour) &
       a.Time('2011-01-01', '2011-01-02'))

wave = a.Wavelength(30 * u.nm, 31 * u.nm)

results = Fido.search(stereo | aia, wave)
print(results)

downloader = parfive.Downloader(loop=asyncio.get_event_loop())
res = Fido.fetch(results, path='./{file}', downloader=downloader)
```

At the time of writing the STEREO part of the query was not returning any results. The output of the script was:
```
Results from 2 Providers:

0 Results from the VSOClient:
Start Time End Time  Source Instrument   Type 
 float64   float64  float64  float64   float64
---------- -------- ------- ---------- -------

1 Results from the VSOClient:
   Start Time [1]       End Time [1]    Source Instrument   Type   Wavelength [2]
                                                                      Angstrom   
       str19               str19         str3     str3      str8      float64    
------------------- ------------------- ------ ---------- -------- --------------
2011-01-01 00:00:08 2011-01-01 00:00:09    SDO        AIA FULLDISK 304.0 .. 304.0


Files Downloaded: 0file [00:00, ?file/s]
Files Downloaded:   0%|                                                                                                                                                                                    | 0/1 [00:00<?, ?file/s]Traceback (most recent call last):
  File "download_coord_data.py", line 20, in <module>
    res = Fido.fetch(results, path='./{file}', downloader=downloader)
  File "/home/stuart/.virtualenvs/sunpy-release/lib/python3.7/site-packages/sunpy/net/fido_factory.py", line 378, in fetch
    results = downloader.download()
  File "/home/stuart/Git/parfive/parfive/downloader.py", line 194, in download
    future = self.run_until_complete(self._run_download(timeouts))
  File "/usr/lib/python3.7/asyncio/base_events.py", line 577, in run_until_complete
    raise RuntimeError('Event loop stopped before Future completed.')
RuntimeError: Event loop stopped before Future completed.
```

The part where it get's really weird is if you swap the order of `aia` and `stereo` around so the fetch line looks like this:
```python
results = Fido.search(aia | stereo, wave)
```
it works without error and happily only downloads the aia image.

**Comment by Cadair** [comment]
So the reason the STEREO download fails is that it shoudn't be `a.Detector` it should be `a.vso.Source`, which at least means the error above should be reproduceable.
