### ISSUE TITLE
Searching JSOC without a PrimeKey fails

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#4049]
It should be possible to search JSOC without a PrimeKey, e.g.
```python
from sunpy.net import Fido, attrs as a
from sunpy.net.jsoc import attrs as jsoca

series = jsoca.Series('hmi.mrsynop_small_720s')

result = Fido.search(series)
```
 but this fails with 
```python
Traceback (most recent call last):
  File "../examples/finding_data/plot_hmi.py", line 11, in <module>
    result = Fido.search(series)
  File "/Users/dstansby/github/sunpy/sunpy/net/fido_factory.py", line 270, in search
    results = query_walker.create(query, self)
  File "/Users/dstansby/github/sunpy/sunpy/net/attr.py", line 466, in create
    return self.createmm(self, *args, **kwargs)
  File "/Users/dstansby/github/sunpy/sunpy/util/functools.py", line 19, in wrapper
    return dispatcher.dispatch(args[1].__class__)(*args, **kwargs)
  File "/Users/dstansby/github/sunpy/sunpy/net/fido_factory.py", line 199, in _create_data
    return factory._make_query_to_client(query)
  File "/Users/dstansby/github/sunpy/sunpy/net/fido_factory.py", line 419, in _make_query_to_client
    results.append(tmpclient.search(*query))
  File "/Users/dstansby/github/sunpy/sunpy/net/jsoc/jsoc.py", line 352, in search
    return_results.append(self._lookup_records(iargs))
  File "/Users/dstansby/github/sunpy/sunpy/net/jsoc/jsoc.py", line 867, in _lookup_records
    ds = self._make_recordset(**iargs)
  File "/Users/dstansby/github/sunpy/sunpy/net/jsoc/jsoc.py", line 791, in _make_recordset
    raise ValueError(error_message)
ValueError: Atleast one PrimeKey must be passed.
```

Doing the following search works fine, even though the time attribute to the search is completely ignored and all the synoptic maps that exist are returned by the search
```python
from sunpy.net import Fido, attrs as a
from sunpy.net.jsoc import attrs as jsoca

time = a.Time('2010/01/01', '2010/01/01')
series = jsoca.Series('hmi.mrsynop_small_720s')

result = Fido.search(time, series)
```

**Comment by nabobalis** [comment]
Was this not tackled by cadair?

**Comment by dstansby** [comment]
Ah yes, I was on sunpy 1.something, with `master` I now get a different error (see above)

**Comment by Cadair** [comment]
Huh, well this undermines my understanding of how DRMS works...

**Comment by dstansby** [comment]
See https://github.com/sunpy/sunpy/pull/4050#issuecomment-619166920 for why this is a won't-fix
