### ISSUE TITLE
OSError: Failed to load return from the HEKClient.

### ISSUE THREAD

**Issue by OlfwayAdbayIgbay** [sunpy/sunpy#4087]
When trying to search for the flares on 2014/10/24 to /25, I get a "Failed to Load Return" error. 
Sunpy Version: 1.1.3

Here's a minimal reproducible example:

```
from sunpy.net import hek
client = hek.HEKClient()
tstart = '2014/10/24 20:50'
tend   = '2014/10/25 00:14'
event_type = 'FL'
client.search(hek.attrs.Time(tstart,tend),hek.attrs.EventType(event_type))
```

```python
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/pytorch/lib/python3.8/site-packages/sunpy/net/hek/hek.py", line 69, in _download
    result = json.load(fd)
  File "/home/user/anaconda3/envs/pytorch/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/home/user/anaconda3/envs/pytorch/lib/python3.8/json/__init__.py", line 343, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc5 in position 33279: invalid continuation byte

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/user/anaconda3/envs/pytorch/lib/python3.8/site-packages/sunpy/net/hek/hek.py", line 99, in search
    return self._download(ndata[0])
  File "/home/user/anaconda3/envs/pytorch/lib/python3.8/site-packages/sunpy/net/hek/hek.py", line 71, in _download
    raise IOError("Failed to load return from the HEKClient.") from e
OSError: Failed to load return from the HEKClient.
```

**Comment by dstansby** [comment]
For the record, this is because byte `0xc5` corresponds to a unicode Angstrom character, which is present in the `.json` that the HEK client is trying to load at this location:

https://www.lmsal.com/hek/her?cosec=2&cmd=search&type=column&event_type=FL&x1=-5000&y1=-5000&x2=5000&y2=5000&event_coordsys=helioprojective&event_starttime=2014-10-24T20%3A50%3A00&event_endtime=2014-10-25T00%3A14%3A00&page=1
