### ISSUE TITLE
RTD is failing

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#4095]
We need to fix RTD. Looks like something related to sample data, so probably needs #4091

**Comment by dstansby** [comment]
The error is
```python
/home/docs/checkouts/readthedocs.org/user_builds/sunpy/conda/latest/lib/python3.8/site-packages/sphinx/deprecation.py:52: RemovedInSphinx40Warning: sphinx.builders.html.DirectoryHTMLBuilder is deprecated. Check CHANGES for Sphinx API modifications.
  return getattr(self._module, name)
/home/docs/checkouts/readthedocs.org/user_builds/sunpy/conda/latest/lib/python3.8/site-packages/readthedocs_ext/readthedocs.py:14: RemovedInSphinx40Warning: sphinx.builders.html.SingleFileHTMLBuilder is deprecated. Check CHANGES for Sphinx API modifications.
  from sphinx.builders.html import (DirectoryHTMLBuilder, SingleFileHTMLBuilder,
/home/docs/checkouts/readthedocs.org/user_builds/sunpy/conda/latest/lib/python3.8/asyncio/base_events.py:654: ResourceWarning: unclosed event loop <_UnixSelectorEventLoop running=False closed=False debug=False>
  _warn(f"unclosed event loop {self!r}", ResourceWarning, source=self)
/home/docs/checkouts/readthedocs.org/user_builds/sunpy/conda/latest/lib/python3.8/asyncio/selector_events.py:694: ResourceWarning: unclosed transport <_SelectorSocketTransport fd=17 read=idle write=<idle, bufsize=0>>
  _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
/home/docs/checkouts/readthedocs.org/user_builds/sunpy/conda/latest/lib/python3.8/asyncio/base_events.py:654: ResourceWarning: unclosed event loop <_UnixSelectorEventLoop running=False closed=False debug=False>
  _warn(f"unclosed event loop {self!r}", ResourceWarning, source=self)
/home/docs/checkouts/readthedocs.org/user_builds/sunpy/conda/latest/lib/python3.8/asyncio/base_events.py:654: ResourceWarning: unclosed event loop <_UnixSelectorEventLoop running=False closed=False debug=False>
  _warn(f"unclosed event loop {self!r}", ResourceWarning, source=self)
/home/docs/checkouts/readthedocs.org/user_builds/sunpy/conda/latest/lib/python3.8/asyncio/base_events.py:654: ResourceWarning: unclosed event loop <_UnixSelectorEventLoop running=False closed=False debug=False>
  _warn(f"unclosed event loop {self!r}", ResourceWarning, source=self)
/home/docs/checkouts/readthedocs.org/user_builds/sunpy/conda/latest/lib/python3.8/asyncio/base_events.py:654: ResourceWarning: unclosed event loop <_UnixSelectorEventLoop running=False closed=False debug=False>
  _warn(f"unclosed event loop {self!r}", ResourceWarning, source=self)
WARNING: /home/docs/checkouts/readthedocs.org/user_builds/sunpy/checkouts/latest/examples/plotting/magnetogram_active_regions.py failed to execute correctly: Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/sunpy/conda/latest/lib/python3.8/site-packages/sphinx_gallery/gen_rst.py", line 460, in _memory_usage
    out = func()
  File "/home/docs/checkouts/readthedocs.org/user_builds/sunpy/conda/latest/lib/python3.8/site-packages/sphinx_gallery/gen_rst.py", line 442, in __call__
    exec(self.code, self.fake_main.__dict__)
  File "/home/docs/checkouts/readthedocs.org/user_builds/sunpy/checkouts/latest/examples/plotting/magnetogram_active_regions.py", line 43, in <module>
    srs_table = srs.read_srs(srs_downloaded_files[0])
  File "/home/docs/checkouts/readthedocs.org/user_builds/sunpy/conda/latest/lib/python3.8/site-packages/sunpy/io/special/srs.py", line 32, in read_srs
    with open(filepath) as srs:
FileNotFoundError: [Errno 2] No such file or directory: '/home/docs/sunpy/data/20170125SRS.txt'
```

I don't think this is sample data, it's data that Fido downloads (or is supposed to download).

**Comment by nabobalis** [comment]
DId our LFS storage update?

That one happens every so often.

**Comment by Cadair** [comment]
Ok well that's a different error to when I last checked :facepalm:

**Comment by rutujasurve94** [comment]
Hi, I've submitted PR for issue #4091. Hopefully this helps wrt RTD failure as well.
