### ISSUE TITLE
Fido downloading invalid FITS files for recent AIA data

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#4159]
Running the code below results in downloading a FITS file that is invalid and can't be loaded by `Map` (see error message below). I think this is a problem for recent AIA data (ie. data that hasn't yet been processed into http://jsoc2.stanford.edu/data/aia/synoptic/, but is present at http://jsoc2.stanford.edu/data/aia/synoptic/nrt/).

I did not have this problem yesterday, so I think something may have changed on the `JSOC` side.

Running `head bad_file.fits` gives
```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access /data/aia/synoptic/2020/05/12/H0000/AIA20200512_000300_0193.fits
on this server.<br />
</p>
</body></html>
8?536:>F;@7@<9FJOB68NHQQ<FJVHJ[UnMebQmZY^mpoh?r????????????????????????*)@:IOpbPs??????????OHok^????=:M]?_??'k_~????*)[U?e?	p	p	?
```
which confirms that somewhere is trying to access `jsoc2.stanford.edu/data/aia/synoptic/2020/05/12/H0000`, which doesn't exist.

```python
import astropy.units as u
from sunpy.net import Fido, attrs as a
from datetime import datetime, timedelta
from sunpy.map import Map

dtime = datetime.now()

query = (a.Time(dtime - timedelta(days=1), dtime, dtime),
         a.Instrument('AIA'),
         a.Wavelength(193 * u.Angstrom))
result = Fido.search(*query)
print(result)
mappath = Fido.fetch(result[0, 0])[0]
m = Map(mappath)
```

```python
Results from 1 Provider:

1 Results from the VSOClient:
   Start Time [1]       End Time [1]    Source Instrument   Type   Wavelength [2]
                                                                      Angstrom   
       str19               str19         str3     str3      str8      float64    
------------------- ------------------- ------ ---------- -------- --------------
2020-05-13 11:09:00 2020-05-13 11:09:00    SDO        AIA FULLDISK 193.0 .. 193.0


Files Downloaded: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.64s/file]
WARNING: non-ASCII characters are present in the FITS file header and have been replaced by "?" characters [astropy.io.fits.util]                                                                              
Traceback (most recent call last):
  File "/Users/dstansby/miniconda3/lib/python3.8/site-packages/astropy/io/fits/hdu/base.py", line 406, in _readfrom_internal
    header_str, header = _BasicHeader.fromfile(data)
  File "/Users/dstansby/miniconda3/lib/python3.8/site-packages/astropy/io/fits/header.py", line 2077, in fromfile
    header_str, cards = parse_header(fileobj)
  File "astropy/io/fits/_utils.pyx", line 38, in astropy.io.fits._utils.parse_header
UnicodeDecodeError: 'ascii' codec can't decode byte 0x82 in position 1171: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 14, in <module>
    m = Map(mappath)
  File "/Users/dstansby/miniconda3/lib/python3.8/site-packages/sunpy/map/map_factory.py", line 274, in __call__
    data_header_pairs, already_maps = self._parse_args(*args, **kwargs)
  File "/Users/dstansby/miniconda3/lib/python3.8/site-packages/sunpy/map/map_factory.py", line 223, in _parse_args
    pairs = self._read_file(path, **kwargs)
  File "/Users/dstansby/miniconda3/lib/python3.8/site-packages/sunpy/map/map_factory.py", line 132, in _read_file
    pairs = read_file(os.fspath(fname), **kwargs)
  File "/Users/dstansby/miniconda3/lib/python3.8/site-packages/sunpy/io/file_tools.py", line 86, in read_file
    return _readers[readername].read(filepath, **kwargs)
  File "/Users/dstansby/miniconda3/lib/python3.8/site-packages/sunpy/io/fits.py", line 67, in read
    with fits.open(filepath, ignore_blank=True, memmap=memmap) as hdulist:
  File "/Users/dstansby/miniconda3/lib/python3.8/site-packages/astropy/io/fits/hdu/hdulist.py", line 164, in fitsopen
    return HDUList.fromfile(name, mode, memmap, save_backup, cache,
  File "/Users/dstansby/miniconda3/lib/python3.8/site-packages/astropy/io/fits/hdu/hdulist.py", line 403, in fromfile
    return cls._readfrom(fileobj=fileobj, mode=mode, memmap=memmap,
  File "/Users/dstansby/miniconda3/lib/python3.8/site-packages/astropy/io/fits/hdu/hdulist.py", line 1079, in _readfrom
    read_one = hdulist._read_next_hdu()
  File "/Users/dstansby/miniconda3/lib/python3.8/site-packages/astropy/io/fits/hdu/hdulist.py", line 1154, in _read_next_hdu
    hdu = _BaseHDU.readfrom(fileobj, **kwargs)
  File "/Users/dstansby/miniconda3/lib/python3.8/site-packages/astropy/io/fits/hdu/base.py", line 325, in readfrom
    hdu = cls._readfrom_internal(fileobj, checksum=checksum,
  File "/Users/dstansby/miniconda3/lib/python3.8/site-packages/astropy/io/fits/hdu/base.py", line 413, in _readfrom_internal
    header = Header.fromfile(data,
  File "/Users/dstansby/miniconda3/lib/python3.8/site-packages/astropy/io/fits/header.py", line 513, in fromfile
    return cls._from_blocks(block_iter, is_binary, sep, endcard,
  File "/Users/dstansby/miniconda3/lib/python3.8/site-packages/astropy/io/fits/header.py", line 596, in _from_blocks
    raise OSError('Header missing END card.')
OSError: Header missing END card.
Exception ignored in: <function VSOClient.__del__ at 0x11c2ace50>
Traceback (most recent call last):
  File "/Users/dstansby/miniconda3/lib/python3.8/site-packages/sunpy/net/vso/vso.py", line 920, in __del__
  File "/Users/dstansby/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 733, in close
  File "/Users/dstansby/miniconda3/lib/python3.8/site-packages/requests/adapters.py", line 325, in close
  File "/Users/dstansby/miniconda3/lib/python3.8/site-packages/urllib3/poolmanager.py", line 211, in clear
  File "/Users/dstansby/miniconda3/lib/python3.8/site-packages/urllib3/_collections.py", line 94, in clear
TypeError: 'NoneType' object is not callable

**Comment by ayshih** [comment]
Not directly related, but I'll cross-reference to #3505 because at least at one time it was possible to download NRT data through Fido, and those NRT files were openable by `Map`, but not without interpretation issues (observer location).

**Comment by ejm4567** [comment]
I was able to run the code above and get the file and it seems fine. 

Results from 1 Provider:

1 Results from the VSOClient:
   Start Time [1]       End Time [1]    Source Instrument   Type   Wavelength [2]
                                                                      Angstrom
       str19               str19         str3     str3      str8      float64
------------------- ------------------- ------ ---------- -------- --------------
2020-05-13 08:54:00 2020-05-13 08:54:00    SDO        AIA FULLDISK 193.0 .. 193.0


Files Downloaded: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:37<00:00, 37.22s/file]



After I get m from Map, what's the best way to test that variable ?

**Comment by jhourcle** [comment]
The file in question is actually at the SDAC :  https://sdo5.nascom.nasa.gov/data/aia/synoptic/2020/05/12/H0000/AIA20200512_000300_0193.fits

I don't have access to that machine any more, but I want to say that there's a cronjob that does an rsync to a machine at LMSAL.  So it's possible that something got corrupted at LMSAL (maybe they pull from the JSOC using HTTP?), but then got fixed, so SDAC then rsynced the fixed file.

**Comment by dstansby** [comment]
Hmm, running the code above is still giving me the same error as above. The Fido search output is
```
1 Results from the VSOClient:
   Start Time [1]       End Time [1]    Source Instrument   Type   Wavelength [2]
                                                                      Angstrom   
       str19               str19         str3     str3      str8      float64    
------------------- ------------------- ------ ---------- -------- --------------
2020-05-15 09:27:00 2020-05-15 09:27:00    SDO        AIA FULLDISK 193.0 .. 193.0
```

**Comment by dstansby** [comment]
See #4327; fixed.
