### ISSUE TITLE
ModuleNotFoundError: No module named 'importlib_metadata'

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#4314]
On `pfsspy` readthedocs builds I'm seeing the below error, which I think is new since sunpy 2.0. It looks like the issue is a hard requirement that `importlib_metadata` is installed, but that is not necessarily the case. The offending code was introduced by https://github.com/sunpy/sunpy/pull/4223.

```python
Unexpected failing examples:
/home/docs/checkouts/readthedocs.org/user_builds/pfsspy/checkouts/latest/examples/finding_data/plot_hmi.py failed leaving traceback:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pfsspy/envs/latest/lib/python3.7/site-packages/sphinx_gallery/gen_gallery.py", line 159, in call_memory
    return 0., func()
  File "/home/docs/checkouts/readthedocs.org/user_builds/pfsspy/envs/latest/lib/python3.7/site-packages/sphinx_gallery/gen_rst.py", line 466, in __call__
    exec(self.code, self.fake_main.__dict__)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pfsspy/checkouts/latest/examples/finding_data/plot_hmi.py", line 23, in <module>
    from sunpy.net import Fido, attrs as a
  File "/home/docs/checkouts/readthedocs.org/user_builds/pfsspy/envs/latest/lib/python3.7/site-packages/sunpy/net/__init__.py", line 4, in <module>
    from sunpy.net import dataretriever as _
  File "/home/docs/checkouts/readthedocs.org/user_builds/pfsspy/envs/latest/lib/python3.7/site-packages/sunpy/net/dataretriever/__init__.py", line 11, in <module>
    from .client import GenericClient, QueryResponse, QueryResponseBlock
  File "/home/docs/checkouts/readthedocs.org/user_builds/pfsspy/envs/latest/lib/python3.7/site-packages/sunpy/net/dataretriever/client.py", line 12, in <module>
    from sunpy.net._attrs import Time, Wavelength
  File "/home/docs/checkouts/readthedocs.org/user_builds/pfsspy/envs/latest/lib/python3.7/site-packages/sunpy/net/_attrs.py", line 14, in <module>
    from .attr import Range, SimpleAttr
  File "/home/docs/checkouts/readthedocs.org/user_builds/pfsspy/envs/latest/lib/python3.7/site-packages/sunpy/net/attr.py", line 28, in <module>
    from sunpy.extern import inflect
  File "/home/docs/checkouts/readthedocs.org/user_builds/pfsspy/envs/latest/lib/python3.7/site-packages/sunpy/extern/inflect.py", line 57, in <module>
    import importlib_metadata
ModuleNotFoundError: No module named 'importlib_metadata'
```

**Comment by Cadair** [comment]
Whoops.

**Comment by nabobalis** [comment]
Whoops indeed.

**Comment by Cadair** [comment]
How did nothing find this?!

**Comment by nabobalis** [comment]
Clearly something is working on our CI as we expect.

**Comment by Cadair** [comment]
or one of our deps pulls this in and somehow @dstansby hasn't got that installed?

**Comment by nabobalis** [comment]
Good point.

**Comment by nabobalis** [comment]
If i do `pip install .[all]` under a python 3.7, something does indeed pull `importlib-metadata-1.6.1`
