### ISSUE TITLE
Creation of XRS TimeSeries results in TypeError

### ISSUE THREAD

**Issue by larrymanley** [sunpy/sunpy#5076]
Upon running "goes_xrs_example.py" get the following error:

```
(base) D:\source>python goes_xrs_example.py
C:\Users\jupit\anaconda3\lib\site-packages\astropy\table\table.py:3183: FutureWarning: elementwise == comparison failed and returning scalar instead; this will raise an error or perform elementwise comparison in the future.
  result = self.as_array() == other
Results from 1 Provider:

3 Results from the XRSClient:
       Start Time               End Time        Instrument ... Source Provider
----------------------- ----------------------- ---------- ... ------ --------
2015-06-21 00:00:00.000 2015-06-21 23:59:59.999        XRS ...   GOES     NOAA
2015-06-21 00:00:00.000 2015-06-21 23:59:59.999        XRS ...   GOES     NOAA
2015-06-21 00:00:00.000 2015-06-21 23:59:59.999        XRS ...   GOES     NOAA


Results from 1 Provider:

1 Results from the XRSClient:
       Start Time               End Time        Instrument ... Source Provider
----------------------- ----------------------- ---------- ... ------ --------
2015-06-21 00:00:00.000 2015-06-21 23:59:59.999        XRS ...   GOES     NOAA


Files Downloaded:   0%|                                                                                | 0/1 [00:00<?, ?file/s]C:\Users\jupit\anaconda3\lib\site-packages\aiohttp-4.0.0a1-py3.7-win-amd64.egg\aiohttp\client.py:977: RuntimeWarning: coroutine 'noop' was never awaited
  self._resp.release()
Files Downloaded: 100%|████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.41file/s]
Future exception was never retrieved
future: <Future finished exception=SSLError(1, '[SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2691)')>
Traceback (most recent call last):
  File "C:\Users\jupit\anaconda3\lib\asyncio\sslproto.py", line 530, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "C:\Users\jupit\anaconda3\lib\asyncio\sslproto.py", line 207, in feed_ssldata
    self._sslobj.unwrap()
  File "C:\Users\jupit\anaconda3\lib\ssl.py", line 778, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2691)
Traceback (most recent call last):
  File "goes_xrs_example.py", line 72, in <module>
    goes_15 = ts.TimeSeries(file_goes15)
  File "d:\source\sunpy\sunpy\timeseries\timeseries_factory.py", line 406, in __call__
    new_ts = self._check_registered_widgets(filepath=filepath, **kwargs)
  File "d:\source\sunpy\sunpy\timeseries\timeseries_factory.py", line 529, in _check_registered_widgets
    data, meta, units = WidgetType._parse_file(filepath)
**TypeError: cannot unpack non-iterable NotImplementedType object**

```
Working with current sunpy master.
Python: 3.7.9
NumPy: 1.19.2
SciPy: 1.6.1
matplotlib: 3.3.4
Astropy: 4.2
Pandas: 1.2.3
parfive: 1.2.0
h5py:  2.10.0
h5netcdf:  0.10.0

The 'nc' file downloads OK.  Tested on Windows, Mac, and Linux with the same error.

**Comment by jeffreypaul15** [comment]
as per #4592 the `source='xrs'` keyword should be specified when working with netcdf files.

**Comment by nabobalis** [comment]
We need to work on replacing that error message. 

Can you try adding, `, source='xrs'` to the "TimeSeries" call and if that fixes it.

**Comment by larrymanley** [comment]
Updating to h5py 3.2.1 fixes it.

Adding `source='xrs'` or `source='XRS'` results in:

```
Traceback (most recent call last):
  File "goes_xrs_example.py", line 72, in <module>
    goes_15 = ts.TimeSeries(file_goes15, source='xrs')
  File "d:\source\sunpy\sunpy\timeseries\timeseries_factory.py", line 406, in __call__
    new_ts = self._check_registered_widgets(filepath=filepath, **kwargs)
  File "d:\source\sunpy\sunpy\timeseries\timeseries_factory.py", line 529, in _check_registered_widgets
    data, meta, units = WidgetType._parse_file(filepath)
  File "d:\source\sunpy\sunpy\timeseries\sources\goes.py", line 139, in _parse_file
    return cls._parse_netcdf(filepath)
  File "d:\source\sunpy\sunpy\timeseries\sources\goes.py", line 207, in _parse_netcdf
    with h5netcdf.File(filepath, mode="r", **XRSTimeSeries._netcdf_read_kw) as d:
  File "C:\Users\jupit\anaconda3\lib\site-packages\h5netcdf\core.py", line 710, in __init__
    self._h5file = h5py.File(path, mode, **kwargs)
  File "C:\Users\jupit\anaconda3\lib\site-packages\h5py\_hl\files.py", line 405, in __init__
    fapl = make_fapl(driver, libver, rdcc_nslots, rdcc_nbytes, rdcc_w0, **kwds)
  File "C:\Users\jupit\anaconda3\lib\site-packages\h5py\_hl\files.py", line 127, in make_fapl
    raise TypeError(msg)
TypeError: 'decode_vlen_strings' is an invalid keyword argument for this function
```

Should this be filed as a separate issue?

**Comment by nabobalis** [comment]
Looks like we might need to pin a higher min version for it.

**Comment by dstansby** [comment]
Hmm, I just installed h5py 2.10.0 and it seemed to work fine for me.

**Comment by dstansby** [comment]
Looking at the error message, I think the download failed somehow, so if you remove the file and try again it should work. Since it sounds like you've got it working I'm going to close this, but feel free to leave a comment if it comes up again and I'll re-open it.

**Comment by nabobalis** [comment]
Yeah I forgot to post as well.

I downloaded the file and used h5py 2.10.0 on a python 3.7 test env with no issues. 
Unfortunately I was unable to replicate it.
