### ISSUE TITLE
Can't create FITS header with `HeliographicCarrington(observer='self')`

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#5262]
https://github.com/sunpy/sunpy/pull/4659 introduced the ability to create a `HeliographicCarrington` coordinate with `observer='self'`. I've just tried using this as a reference coordinate for `make_fitswcs_header`, but it errors out (see below)

I think the fix here is to set the auxillary information on the WCS to have the same `rsun_obs` as the coordinate, and 
arbitrary observer lat/lon.

This is present in both 2.1.x and on master.

```python
import sunpy.map
from sunpy.coordinates import HeliographicCarrington
import sunpy.sun.constants
import astropy.units as u

ref_coord = HeliographicCarrington(0*u.deg, 0*u.deg, sunpy.sun.constants.radius,
                                   obstime='2020-01-01',
                                   observer='self')
shape_out = (360, 720)
header = sunpy.map.make_fitswcs_header(shape_out, ref_coord,
                                       scale=[180 / shape_out[0],
                                              360 / shape_out[1]] * u.deg / u.pix,
                                       projection_code="CAR")
out_wcs = WCS(header)
print(out_wcs.wcs.aux)
```

```python
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    header = sunpy.map.make_fitswcs_header(shape_out, ref_coord,
  File "/Users/dstansby/miniconda3/lib/python3.8/site-packages/astropy/units/decorators.py", line 251, in wrapper
    return_ = wrapped_function(*func_args, **func_kwargs)
  File "/Users/dstansby/github/sunpy/sunpy/map/header_helper.py", line 165, in make_fitswcs_header
    coordinate.rsun, coordinate.observer.radius
AttributeError: 'str' object has no attribute 'radius'
(base) Davids-MBP-3:sunpy dstansby$ python test.py 
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    header = sunpy.map.make_fitswcs_header(shape_out, ref_coord,
  File "/Users/dstansby/miniconda3/lib/python3.8/site-packages/astropy/units/decorators.py", line 251, in wrapper
    return_ = wrapped_function(*func_args, **func_kwargs)
  File "/Users/dstansby/github/sunpy/sunpy/map/header_helper.py", line 165, in make_fitswcs_header
    coordinate.rsun, coordinate.observer.radius
AttributeError: 'str' object has no attribute 'radius'
```

**Comment by ayshih** [comment]
Can the fix could just be:
```
         meta_wcs['rsun_obs'] = sun._angular_radius(
-            coordinate.rsun, coordinate.observer.radius
+            coordinate.rsun, getattr(coordinate.observer, 'radius', coordinate.radius)
         ).to_value(u.arcsec)
```
(The only time that `coordinate.observer` would not have the attribute `radius` is if it is the string `'self'` for an HGC coordinate, and then we can just grab `radius` from the coordinate itself.)
