### ISSUE TITLE
Improve error message when trying to specify `observer='self'` without a radial coordinate

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#5356]
It is possible to construct a `HeliographicCarrington(lon, lat, observer='self')` coordinate without specifying the radial distance. This means that the observer is not well defined however, which currently silently passes at initiation, but can cause runtime errors that are not user-friendly (see below for an example).

So, I think trying to create `HeliographicCarrington(lon, lat, observer='self')` should probably error when initiated? @ayshih do you have any thoughts?

```python
from astropy.coordinates import SkyCoord
import astropy.units as u
import sunpy.map

obstime = '2000-1-1'
shape = [180, 360]

frame_out = SkyCoord(
    0 * u.deg, 0 * u.deg, obstime=obstime,
    frame="heliographic_carrington", observer='self')
# Construct header
header = sunpy.map.make_fitswcs_header(
    shape, frame_out,
    scale=[360 / shape[0],
           180 / shape[1]] * u.deg / u.pix,
    reference_pixel=[(shape[0] / 2) - 0.5,
                     (shape[1] / 2) - 0.5] * u.pix,
    projection_code="CEA")
```

```python
Traceback (most recent call last):
  File "/Users/dstansby/miniconda3/envs/dev/lib/python3.9/site-packages/astropy/units/quantity.py", line 740, in to_value
    scale = self.unit._to(unit)
  File "/Users/dstansby/miniconda3/envs/dev/lib/python3.9/site-packages/astropy/units/core.py", line 950, in _to
    raise UnitConversionError(
astropy.units.core.UnitConversionError: 'Unit(dimensionless)' is not a scaled version of 'Unit("m")'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dstansby/github/sunpy/test.py", line 12, in <module>
    header = sunpy.map.make_fitswcs_header(
  File "/Users/dstansby/miniconda3/envs/dev/lib/python3.9/site-packages/astropy/units/decorators.py", line 252, in wrapper
    return_ = wrapped_function(*func_args, **func_kwargs)
  File "/Users/dstansby/github/sunpy/sunpy/map/header_helper.py", line 128, in make_fitswcs_header
    meta_wcs = _get_wcs_meta(coordinate, projection_code)
  File "/Users/dstansby/github/sunpy/sunpy/map/header_helper.py", line 197, in _get_wcs_meta
    skycoord_wcs = astropy.wcs.utils.celestial_frame_to_wcs(coordinate, projection_code)
  File "/Users/dstansby/miniconda3/envs/dev/lib/python3.9/site-packages/astropy/wcs/utils.py", line 284, in celestial_frame_to_wcs
    wcs = func(frame, projection=projection)
  File "/Users/dstansby/github/sunpy/sunpy/coordinates/wcs_utils.py", line 155, in solar_frame_to_wcs_mapping
    _set_wcs_aux_obs_coord(wcs, observer)
  File "/Users/dstansby/github/sunpy/sunpy/coordinates/wcs_utils.py", line 127, in _set_wcs_aux_obs_coord
    wcs.wcs.aux.dsun_obs = obs_frame.radius.to_value(u.m)
  File "/Users/dstansby/miniconda3/envs/dev/lib/python3.9/site-packages/astropy/units/quantity.py", line 743, in to_value
    value = self._to_value(unit, equivalencies)
  File "/Users/dstansby/miniconda3/envs/dev/lib/python3.9/site-packages/astropy/units/quantity.py", line 662, in _to_value
    return self.unit.to(unit, self.view(np.ndarray),
  File "/Users/dstansby/miniconda3/envs/dev/lib/python3.9/site-packages/astropy/units/core.py", line 987, in to
    return self._get_converter(other, equivalencies=equivalencies)(value)
  File "/Users/dstansby/miniconda3/envs/dev/lib/python3.9/site-packages/astropy/units/core.py", line 918, in _get_converter
    raise exc
  File "/Users/dstansby/miniconda3/envs/dev/lib/python3.9/site-packages/astropy/units/core.py", line 903, in _get_converter
    return self._apply_equivalencies(
  File "/Users/dstansby/miniconda3/envs/dev/lib/python3.9/site-packages/astropy/units/core.py", line 886, in _apply_equivalencies
    raise UnitConversionError(
astropy.units.core.UnitConversionError: '' (dimensionless) and 'm' (length) are not convertible
```

**Comment by dstansby** [comment]
This is because the radius of a `HeliographicCarrington` coordinate defaults to `1.0`. So, I think the above code should error because without a radius specified there isn't enough information for the observer to be 'self'.

**Comment by ayshih** [comment]
> This is because the radius of a `HeliographicCarrington` coordinate defaults to `1.0`(this is odd?), and I haven't manually specified the radius.

This is because `UnitSphericalRepresentation` frequently gets converted to `SphericalRepresentation` with unity magnitude (dimensionless 1.0) in the transformation framework.

> So, I think the above code should error because without a radius specified there isn't enough information for the observer to be 'self'.

Seems reasonable
