### ISSUE TITLE
TypeError: buffer is too small for requested array

### ISSUE THREAD

**Issue by apoorvamanjunath** [sunpy/sunpy#5371]
Hello all,
I am trying to read set of fits files and produce a histogram out of these files to visualize the comanalities among these files. But I get the error "TypeError: buffer is too small for requested array" for few set of files. I am not able to get my head around it. Can anyone help me with this please.
below is the code

```python
import sunpy.map
import matplotlib.pyplot as plt
import numpy as np
import sys
import os

file='aia_lev1_94a'
directory = '................/allwavength_2014_04'

# calculate histogram
hist = {}
for filename in os.listdir(directory):
    if filename.endswith(".fits"):
        if filename.startswith("aia_lev1_193a"):
            aia=sunpy.map.Map(filename)
            for i,item in enumerate(aia.data):
               for j,item1 in enumerate(item):
                    if (item1 not in hist):
                           hist[item1] = 1
                    else:
                           hist[item1] += 1

print(len(hist))
plt.bar(list(hist.keys()), hist.values(), width=20, color='b')
plt.yscale('log')
plt.show()
plt.savefig("histogram_" + file + ".png")

```

**Comment by nabobalis** [comment]
What part errors?

Without the files it is hard to replicate, it could be those files are corrupted and need to be reacquired.

**Comment by apoorvamanjunath** [comment]
> What part errors?
> 
> Without the files it is hard to replicate, it could be those files are corrupted and need to be reacquired.

This is the error I am getting,
 
WARNING: File may have been truncated: actual file length (2539520) is smaller than the expected size (9000000) [astropy.io.fits.file]
Traceback (most recent call last):
  File "test.py", line 21, in <module>
    aia=sunpy.map.Map(filename)
  File "/home/manj_ap/.local/lib/python2.7/site-packages/sunpy/map/map_factory.py", line 297, in __call__
    data_header_pairs, already_maps = self._parse_args(*args, **kwargs)
  File "/home/manj_ap/.local/lib/python2.7/site-packages/sunpy/map/map_factory.py", line 209, in _parse_args
    pairs = self._read_file(path, **kwargs)
  File "/home/manj_ap/.local/lib/python2.7/site-packages/sunpy/map/map_factory.py", line 133, in _read_file
    pairs = read_file(fname, **kwargs)
  File "/home/manj_ap/.local/lib/python2.7/site-packages/sunpy/io/file_tools.py", line 85, in read_file
    return _readers[readername].read(filepath, **kwargs)
  File "/home/manj_ap/.local/lib/python2.7/site-packages/sunpy/io/fits.py", line 89, in read
    pairs.append(HDPair(hdu.data, header))
  File "/home/manj_ap/.local/lib/python2.7/site-packages/astropy/utils/decorators.py", line 770, in __get__
    val = self.fget(obj)
  File "/home/manj_ap/.local/lib/python2.7/site-packages/astropy/io/fits/hdu/compressed.py", line 1378, in data
    data = compression.decompress_hdu(self)
  File "/home/manj_ap/.local/lib/python2.7/site-packages/astropy/utils/decorators.py", line 770, in __get__
    val = self.fget(obj)
  File "/home/manj_ap/.local/lib/python2.7/site-packages/astropy/io/fits/hdu/compressed.py", line 1430, in compressed_data
    compressed_data = super(BinTableHDU, self).data
  File "/home/manj_ap/.local/lib/python2.7/site-packages/astropy/utils/decorators.py", line 770, in __get__
    val = self.fget(obj)
  File "/home/manj_ap/.local/lib/python2.7/site-packages/astropy/io/fits/hdu/table.py", line 349, in data
    data = self._get_tbdata()
  File "/home/manj_ap/.local/lib/python2.7/site-packages/astropy/io/fits/hdu/table.py", line 165, in _get_tbdata
    self._data_offset)
  File "/home/manj_ap/.local/lib/python2.7/site-packages/astropy/io/fits/hdu/base.py", line 480, in _get_raw_data
    return self._file.readarray(offset=offset, dtype=code, shape=shape)
  File "/home/manj_ap/.local/lib/python2.7/site-packages/astropy/io/fits/file.py", line 285, in readarray
    buffer=self._mmap)
TypeError: buffer is too small for requested array

**Comment by nabobalis** [comment]
Looking at that, I still think that a file is a broken file on disk and it is causing that error.

The other thing is that, sunpy nor astropy support python 2.7 anymore, so you must be using quite old versions of those packages as well.

**Comment by dstansby** [comment]
Yes, I often see this error when a file download has not completed fully. I think you will need to re-download your file. I will close as this isn't a problem with sunpy, but feel free to leave a comment if re-downloading the file doesn't work and we can re-open the issue.
