### ISSUE TITLE
No way to specify line colors for a CompositeMap plot that includes contours

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#5455]
If I want to specify the line colours of a contour map using `CompositeMap`, I think the correct code is:

```python
import matplotlib.pyplot as plt

import astropy.units as u
from astropy.coordinates import SkyCoord

import sunpy.data.sample
import sunpy.map

aia_map = sunpy.map.Map(sunpy.data.sample.AIA_171_IMAGE)
hmi_map = sunpy.map.Map(sunpy.data.sample.HMI_LOS_IMAGE)
comp_map = sunpy.map.Map(aia_map, hmi_map, composite=True)

comp_map.set_levels(index=1, levels=[-1000, -500, -250, 250, 500, 1000] * u.G)

fig = plt.figure()
ax = plt.subplot(projection=aia_map)
comp_map.plot(colors='black')
plt.show()
```

This fails however, as the keyword arguments given to `comp_map.plot()` are handed to *both* calls to `plot()` and `draw_contours()`, and an error is raised when `.plot(colors='black')` is passed (see below). The fix here is to work out a way to hand both `plot` and `draw_contours` keyword arguments separately to `CompositeMap.plot()`.

```python
Traceback (most recent call last):
  File "/Users/dstansby/github/sunpy/test.py", line 19, in <module>
    comp_map.plot(linewidths=1, colors='black')
  File "/Users/dstansby/github/sunpy/sunpy/map/compositemap.py", line 419, in plot
    ret.append(m.plot(**params))
  File "/Users/dstansby/github/astropy/astropy/units/decorators.py", line 253, in wrapper
    return_ = wrapped_function(*func_args, **func_kwargs)
  File "/Users/dstansby/github/sunpy/sunpy/map/mapbase.py", line 2467, in plot
    ret = axes.pcolormesh(data, **imshow_args)
  File "/Users/dstansby/miniconda3/envs/dev/lib/python3.9/site-packages/matplotlib/__init__.py", line 1361, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/Users/dstansby/miniconda3/envs/dev/lib/python3.9/site-packages/matplotlib/axes/_axes.py", line 6192, in pcolormesh
    collection = mcoll.QuadMesh(Nx - 1, Ny - 1, coords,
  File "/Users/dstansby/miniconda3/envs/dev/lib/python3.9/site-packages/matplotlib/collections.py", line 1996, in __init__
    super().__init__(**kwargs)
  File "/Users/dstansby/miniconda3/envs/dev/lib/python3.9/site-packages/matplotlib/_api/deprecation.py", line 431, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "/Users/dstansby/miniconda3/envs/dev/lib/python3.9/site-packages/matplotlib/collections.py", line 217, in __init__
    self.update(kwargs)
  File "/Users/dstansby/miniconda3/envs/dev/lib/python3.9/site-packages/matplotlib/artist.py", line 1062, in update
    raise AttributeError(f"{type(self).__name__!r} object "
AttributeError: 'QuadMesh' object has no property 'colors'
```

**Comment by ConorMacBride** [comment]
There's code in `CompositeMap.plot()` already to handle `linewidths`:
https://github.com/sunpy/sunpy/blob/112dab490ef9a43078872583208210de7940d1c3/sunpy/map/compositemap.py#L406-L410
So this can be fixed by adding `colors` to the same list.

I'm trying to think what else we could add to this list. The most obvious to me would be `linestyles`, although there are many other parameters that someone would conceivably want to apply to images or contours or both, and I don't think it will always be clear which. (For example, matplotlib `pcolormesh` accepts `linewidth`, `linewidths`, `lw`, `color`, `linestyle`, `linestyles` and `ls`, while `imshow` accepts none of those, and `contour` only accepts `linewidths`, `colors` and `linestyles`.)

I propose we use the following list of contour-only parameters, and add to the docstring that linewidth/style/color related parameters are only used when plotting contour maps, so it is clearer.

`['linewidth', 'linewidths', 'lw', 'color', 'colors', 'c', 'linestyle', 'linestyles', 'ls']`

So these kwargs will only be passed to the matplotlib contour function. And matplotlib will raise a `UserWarning: The following kwargs were not used by contour: 'c'` for anything in this list other than `linewidths`, `colors` and `linestyles`.

What do you think?
