### ISSUE TITLE
QueryResponse.show fails with 24:00:00 in timestamp

### ISSUE THREAD

**Issue by derdon** [sunpy/sunpy#568]
The following query results in a `QueryResponse` that cannot be displayed using the `show` method:

```
>>> from sunpy.net import vso
>>> client = vso.VSOClient()
>>> qr = client.query(vso.attrs.Time('2013-05-18 23:59:00', '2013-05-19'))
>>> qr.num_records()
122
>>> qr.show()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/derdon/repos/python/3rdparty/sunpy/sunpy/net/vso/vso.py", line 223, in show
    ] for record in self]
  File "/home/derdon/anaconda/lib/python2.7/_strptime.py", line 328, in _strptime
    data_string[found.end():])
ValueError: unconverted data remains: 0
```

I debugged the values of `qr` and found out that the timestamp(s) with "240000" are the cause for the exception:

```
>>> from datetime import datetime
>>> for block in qr:
...     x = datetime.strptime(block.time.start, '%Y%m%d%H%M%S')
>>> for block in qr:
...     x = datetime.strptime(block.time.end, '%Y%m%d%H%M%S')
Traceback (most recent call last):
  File "<input>", line 2, in <module>
  File "/home/derdon/anaconda/lib/python2.7/_strptime.py", line 328, in _strptime
    data_string[found.end():])
ValueError: unconverted data remains: 0
>>> block.time.end
20130518240000
>>> datetime.strptime(block.time.end, '%Y%m%d%H%M%S')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/derdon/anaconda/lib/python2.7/_strptime.py", line 328, in _strptime
    data_string[found.end():])
ValueError: unconverted data remains: 0
```

My proposal is to use the `sunpy.time.time._regex_parse_time` function somehow (or adjust sunpy.time.parse_time so that the time format `sunpy.net.vso.attrs.TIMEFORMAT` is supported as well). See:

```
>>> sunpy.time.time._regex_parse_time(block.time.end, '%Y%m%d%H%M%S')
(u'20130518000000', datetime.timedelta(1))
```

**Comment by dpshelio** [comment]
I've just tried this query (0.9.5) and found maybe some other problem... If I don't specify instrument it returns nothing, if I do it works as expected.

```python
>>> from sunpy.net import vso               
>>> client = vso.VSOClient()
>>> qr = client.search(vso.attrs.Time('2013-05-18 23:59:00', '2013-05-19'))
>>> print(len(qr))
>>> qr                                  
0
<QTable length=0>   
Start Time End Time  Source Instrument   Type     
float64   float64  float64  float64   float64
---------- -------- ------- ---------- -------
```

**Comment by Cadair** [comment]
I think we removed `.show()` from `vso.QueryResponse`?

@dpshelio You should open a separate issue about querying without instrument, I think it's a use case which is poorly supported.

**Comment by Cadair** [comment]
Yep, this is no longer a method on `QueryResponse`
