### ISSUE TITLE
Downloading cutouts example failing on gallery docs build

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#6510]
### Describe the bug

In the gallery docs build the "downloading AIA cutouts" example is failing very often at the moment with the error message:
```python
 generating gallery for generated/gallery/acquiring_data... [ 80%] downloading_cutouts.py
WARNING: /home/runner/work/sunpy/sunpy/examples/acquiring_data/downloading_cutouts.py failed to execute correctly: Traceback (most recent call last):
  File "/home/runner/work/sunpy/sunpy/examples/acquiring_data/downloading_cutouts.py", line 34, in <module>
    amap = sunpy.map.Map(files)
  File "/home/runner/work/sunpy/sunpy/.tox/build_docs-gallery/lib/python3.8/site-packages/sunpy/map/map_factory.py", line 340, in __call__
Error:     raise RuntimeError('No maps loaded')
RuntimeError: No maps loaded
```

I would propose we disable this example from running in the gallery for now, unless someone can come up with a quick fix. Whenver I try and run this example locally it seems to work fine.

### To Reproduce

import sunpy

sunpy.map.Map(...)
etc

**Comment by dstansby** [comment]
This is happening again...
