### ISSUE TITLE
`get_horizons_coord` failing

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#6550]
### Describe the bug

`get_horizons_coord` is failing on the CI. The example build has this traceback:
```python
 /home/runner/work/sunpy/sunpy/examples/units_and_coordinates/getting_lasco_observer_location.py failed leaving traceback:
Traceback (most recent call last):
  File "/home/runner/work/sunpy/sunpy/examples/units_and_coordinates/getting_lasco_observer_location.py", line 69, in <module>
    soho = get_horizons_coord('SOHO', lasco_map.date)
  File "/home/runner/work/sunpy/sunpy/.tox/build_docs-gallery/lib/python3.8/site-packages/sunpy/coordinates/ephemeris.py", line 317, in get_horizons_coord
    raise e
  File "/home/runner/work/sunpy/sunpy/.tox/build_docs-gallery/lib/python3.8/site-packages/sunpy/coordinates/ephemeris.py", line 313, in get_horizons_coord
    result = query.vectors()
  File "/home/runner/work/sunpy/sunpy/.tox/build_docs-gallery/lib/python3.8/site-packages/astroquery/utils/class_or_instance.py", line 25, in f
    return self.fn(obj, *args, **kwds)
  File "/home/runner/work/sunpy/sunpy/.tox/build_docs-gallery/lib/python3.8/site-packages/astroquery/utils/process_asyncs.py", line 29, in newmethod
    result = self._parse_result(response, verbose=verbose)
  File "/home/runner/work/sunpy/sunpy/.tox/build_docs-gallery/lib/python3.8/site-packages/astroquery/jplhorizons/core.py", line 1295, in _parse_result
    data = self._parse_horizons(response.text)
  File "/home/runner/work/sunpy/sunpy/.tox/build_docs-gallery/lib/python3.8/site-packages/astroquery/jplhorizons/core.py", line 1152, in _parse_horizons
    raise ValueError(('Ambiguous target name; provide '
ValueError: Ambiguous target name; provide unique id:
  ID#      Name                               Designation  IAU/aliases/other   
  -------  ---------------------------------- -----------  ------------------- 
       10  Sun                                             Sol                  
      -23  Pioneer 10 (spacecraft)                                              
  -399100  Apollo 10 S-IVB (spacecraft)                                         
  -399101  Apollo 10 LM (spacecraft)                       Snoopy               
 


-------------------------------------------------------------------------------
```

### To Reproduce

import sunpy

sunpy.map.Map(...)
etc

**Comment by ayshih** [comment]
Bug has been fixed by the Horizons folks
