### ISSUE TITLE
Requesting support for GONG H-alpha Maps

### ISSUE THREAD

**Issue by dgarciabriseno** [sunpy/sunpy#6653]
### Describe the bug

This may actually be a feature request.
Attempting to load GONG H-alpha jp2 files results in an error.
Doesn't seem to fall into generic map so a new map definition may have to be written.
It looks like the FITS metadata is missing the CUNIT tags and that might be the cause of the error.

### To Reproduce

Using http://swhv.oma.be/jp2/gong_halpha/2022/12/08/2022_12_08__00_36_12__NSO-GONG_GONG_H-alpha_6562.jp2

```
from sunpy.map import Map
Map("2022_12_08__00_36_12__NSO-GONG_GONG_H-alpha_6562.jp2")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/sunpy/map/map_factory.py", line 331, in __call__
    new_map = self._check_registered_widgets(data, meta, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/sunpy/map/map_factory.py", line 381, in _check_registered_widgets
    return WidgetType(data, meta, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/sunpy/map/mapbase.py", line 232, in __init__
    self._validate_meta()
  File "/usr/local/lib/python3.8/dist-packages/sunpy/map/mapbase.py", line 1409, in _validate_meta
    raise MapMetaValidationError('\n'.join(err_message))
sunpy.map.mapbase.MapMetaValidationError: Image coordinate units for axis 1 not present in metadata.
Image coordinate units for axis 2 not present in metadata.
See https://docs.sunpy.org/en/stable/code_ref/map.html#fixing-map-metadata for instructions on how to add missing metadata.
```

### System Details

==============================
sunpy Installation Information
==============================

General
#######
OS: Ubuntu (20.04, Linux 5.10.104-linuxkit)
Arch: 64bit, (x86_64)
sunpy: 4.1.0
Installation path: /usr/local/lib/python3.8/dist-packages/sunpy-4.1.0.dist-info

Required Dependencies
#####################
astropy: 5.1.1
numpy: 1.23.5
packaging: 21.3
parfive: 2.0.2

Optional Dependencies
#####################
asdf: Missing asdf>=2.8.0; extra == "asdf"
asdf-astropy: Missing asdf-astropy>=0.1.1; extra == "asdf"
beautifulsoup4: 4.11.1
cdflib: Missing cdflib!=0.4.0,>=0.3.19; extra == "timeseries"
dask: Missing dask[array]>=2.0.0; extra == "dask"
drms: 0.6.3
glymur: 0.12.1
h5netcdf: Missing h5netcdf>=0.8.1; extra == "timeseries"
h5py: Missing h5py>=3.1.0; extra == "timeseries"
lxml: 4.9.1
matplotlib: 3.6.2
mpl-animators: Missing mpl-animators>=1.0.0; extra == "map" or "visualization"
pandas: 1.5.2
python-dateutil: 2.8.2
reproject: Missing reproject; extra == "docs" or "map"
scikit-image: Missing scikit-image>=0.16.0; extra == "image"
scipy: 1.9.3
sqlalchemy: Missing sqlalchemy>=1.3.4; extra == "database"
tqdm: 4.64.1
zeep: 4.2.1

### Installation method

pip

**Comment by wafels** [comment]
Hmmm - how does JHelioviewer read and display these JP2 files?

**Comment by samaloney** [comment]
With #6656 merged is this still an issue?

**Comment by nabobalis** [comment]
Will need to verify it works on the JP2 files but hopefully.
