### ISSUE TITLE
Map resampling example failing on CI

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#6739]
### Describe the bug

```python
Unexpected failing examples:
/home/runner/work/sunpy/sunpy/examples/map/map_resampling_and_superpixels.py failed leaving traceback:
Traceback (most recent call last):
  File "/home/runner/work/sunpy/sunpy/examples/map/map_resampling_and_superpixels.py", line 27, in <module>
    aia_resampled_map = aia_map.resample(new_dimensions)
  File "/home/runner/work/sunpy/sunpy/.tox/build_docs-gallery/lib/python3.8/site-packages/astropy/units/decorators.py", line 316, in wrapper
    return_ = wrapped_function(*func_args, **func_kwargs)
  File "/home/runner/work/sunpy/sunpy/.tox/build_docs-gallery/lib/python3.8/site-packages/sunpy/map/mapbase.py", line 1549, in resample
    new_data = sunpy_image_resample(self.data.copy().T, dimensions,
  File "/home/runner/work/sunpy/sunpy/.tox/build_docs-gallery/lib/python3.8/site-packages/sunpy/image/resample.py", line 68, in resample
    data = _resample_nearest_linear(orig, dimensions, method,
  File "/home/runner/work/sunpy/sunpy/.tox/build_docs-gallery/lib/python3.8/site-packages/sunpy/image/resample.py", line 105, in _resample_nearest_linear
    new_data = scipy.interpolate.interpn(old_coords, orig, new_coords,
  File "/home/runner/work/sunpy/sunpy/.tox/build_docs-gallery/lib/python3.8/site-packages/scipy/interpolate/_rgi.py", line 654, in interpn
    return interp(xi)
  File "/home/runner/work/sunpy/sunpy/.tox/build_docs-gallery/lib/python3.8/site-packages/scipy/interpolate/_rgi.py", line 336, in __call__
    result = evaluate_linear_2d(self.values,
  File "_rgi_cython.pyx", line 19, in scipy.interpolate._rgi_cython.__pyx_fused_cpdef
TypeError: No matching signature found
```

### To Reproduce

import sunpy

sunpy.map.Map(...)
etc

**Comment by dstansby** [comment]
Looks like https://github.com/scipy/scipy/issues/17718 is the upstream issue
