### ISSUE TITLE
`map` can't handle certain units (e.g., `u.electron`) in memory due to limitation of FITS

### ISSUE THREAD

**Issue by starfleetjames** [sunpy/sunpy#6823]
### Describe the bug

I'm trying to do some manipulation of a `map`, all in memory, to move from an MHD simulation, through an instrument simulator, and ultimately to saving a FITS file on disk in units of `u.dN`. In that process, there is a point where I am multiplying a `map` with `Unit("ph / (Angstrom cm2 s sr)")` by a quantum yield of the detector with `Unit("electron / ph")`. But that results in this error: 
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/masonjp2/opt/anaconda3/envs/suncet/lib/python3.10/site-packages/sunpy/util/decorators.py", line 403, in inner
    return func(instance, value)
  File "/Users/masonjp2/opt/anaconda3/envs/suncet/lib/python3.10/site-packages/sunpy/map/mapbase.py", line 566, in __mul__
    return self._new_instance_from_op(new_data)
  File "/Users/masonjp2/opt/anaconda3/envs/suncet/lib/python3.10/site-packages/sunpy/map/mapbase.py", line 538, in _new_instance_from_op
    new_meta['bunit'] = new_data.unit.to_string('fits')
  File "/Users/masonjp2/opt/anaconda3/envs/suncet/lib/python3.10/site-packages/astropy/units/core.py", line 739, in to_string
    return f.to_string(self)
  File "/Users/masonjp2/opt/anaconda3/envs/suncet/lib/python3.10/site-packages/astropy/units/format/fits.py", line 113, in to_string
    unit = utils.decompose_to_known_units(unit, cls._get_unit_name)
  File "/Users/masonjp2/opt/anaconda3/envs/suncet/lib/python3.10/site-packages/astropy/units/format/utils.py", line 103, in decompose_to_known_units
    new_unit = new_unit * decompose_to_known_units(base, func) ** power
  File "/Users/masonjp2/opt/anaconda3/envs/suncet/lib/python3.10/site-packages/astropy/units/format/utils.py", line 107, in decompose_to_known_units
    func(unit)
  File "/Users/masonjp2/opt/anaconda3/envs/suncet/lib/python3.10/site-packages/astropy/units/format/fits.py", line 107, in _get_unit_name
    cls._validate_unit(name)
  File "/Users/masonjp2/opt/anaconda3/envs/suncet/lib/python3.10/site-packages/astropy/units/format/fits.py", line 86, in _validate_unit
    raise ValueError(
ValueError: Unit 'electron' not supported by the FITS standard. 
```

### To Reproduce

```python
>>> import astropy.units as u
>>> import sunpy.map
>>> from sunpy.data.sample import AIA_171_IMAGE
>>> aia = sunpy.map.Map(AIA_171_IMAGE)
>>> aia * (1*u.electron)
Traceback (most recent call last):
...
ValueError: Unit 'electron' not supported by the FITS standard.
```
^^^ thanks to @ayshih 

### System Details

- sunpy version: 4.0.1
- astropy version: 5.1

### Installation method

conda

**Comment by ayshih** [comment]
```python
>>> import astropy.units as u
>>> import sunpy.map
>>> from sunpy.data.sample import AIA_171_IMAGE
>>> aia = sunpy.map.Map(AIA_171_IMAGE)
>>> aia * (1*u.electron)
Traceback (most recent call last):
...
ValueError: Unit 'electron' not supported by the FITS standard.
```

**Comment by OussCHE** [comment]
Reading the traceback, I realized that the warning stems from Astropy not handling this type on FITS (hence the warning) . I would love to tackle the issue

**Comment by dstansby** [comment]
I'm going to re-label this a feature request, as I don't think we've ever supported this. I think fixing this is going to depend on a major refactoring of the GenericMap data model which may happen at some point in the future.

**Comment by ankitkhushwaha** [comment]
@nabobalis  This code is working as intended , i think this closes the issue
```
import astropy.units as u
import sunpy.map
from sunpy.data.sample import AIA_171_IMAGE
aia = sunpy.map.Map(AIA_171_IMAGE)
aia * (1*u.electron)
```

**Comment by jmason86** [comment]
Hooray! Thank you so much!!! 

I just verified that while this still did not work in sunpy v5.1.5 it now _does_ work in sunpy v6.0.4. 🎉

**Comment by starfleetjames** [comment]
Uh oh, @ankitkhushwaha and @nabobalis it appears that there are still some issues with certain units. 

```
import astropy.units as u
import sunpy.map
from sunpy.data.sample import AIA_171_IMAGE
aia = sunpy.map.Map(AIA_171_IMAGE)

a_new = aia * (1 * (u.electron / u.DN / u.pix**2))
a_new.unit
```
results in 
```
WARNING: SunpyMetadataWarning: Could not parse unit string "electron / pix2" as a valid FITS unit.
See https://docs.sunpy.org/en/stable/how_to/fix_map_metadata.html for how to fix metadata before loading it with sunpy.map.Map.
See https://fits.gsfc.nasa.gov/fits_standard.html for the FITS unit standards. [sunpy.map.mapbase]
```

I think it makes sense for a warning to be issued but it's not actually storing the unit in memory and as a result you can't do any further manipulations of the unit. I tried a bunch of varieties of units and it's really not clear why some are okay but others are not. For instance, `Unit("ph / pix2")` is okay but `Unit("electron / pix2")` is not.

**Comment by starfleetjames** [comment]
Looks like the issue is in MapBase 
(https://github.com/sunpy/sunpy/blob/930760a154dfd337b9d87b5fdb474218f8626363/sunpy/map/mapbase.py#L802-L808)

I think if that last line were just removed, the issue would go away because the unit wouldn't be overridden with `None`.

**Comment by ankitkhushwaha** [comment]
hey @starfleetjames , since the `aia_map` has `DN` unit  .  warning raised when map is divided by `u.DN` and unit becomes None.
thats why warning is raised.

**Comment by ayshih** [comment]
@starfleetjames: You will not like this, but unfortunately the fact that `aia * (1 * u.electron)` works is a bug.  In #7585, we intended to special-case DN as the only non-FITS unit that was allowed, but the code incorrectly allowed any combination of non-FITS units as long as DN was one of them.  That's why "DN * electron" is currently allowed by "electron" by itself is not.

For our 6.0 line, we have to fix the bug so that both are not allowed and return `None` as the unit (see #8037).

We can discuss whether our 6.1 line can do something different (a la #8035).

**Comment by starfleetjames** [comment]
Well that does make a lot more sense with the code comment in `MapBase` that was just above what I linked to earlier. I'm sure there's some historical reason that FITS didn't support DN but it's necessary because that's what so many of our imagers do. 

Fine by me for 6.1 to be where something different is done. Maybe there are reasons that `map` is so restricted to the FITS standard even when it exists only in memory but I would still argue that it shouldn't be. There are other data formats that are much more permissive (e.g., netCDF, HDF5) so locking the class to conform to the most restrictive one has gotta be causing other limitations like the one here. There's also already some concessions being made like the fact that you can even do `map.unit` instead of having to do something like `map.header['bunit']`. It makes a whole lot of sense to me for warnings and errors to be thrown when trying to write to FITS (or to any other format on disk). 

It occurs to me now also that if there remain really good reasons not to make this change, I could always extend map in my own codebase and overwrite `MapBase` to allow arbitrary units. Hm....

**Comment by starfleetjames** [comment]
Just tested with v7.0.3 and issue still persists (not surprising.. I'm sure this github issue would've been referenced in subsequent release if it had been addressed). No change in behavior from my earlier comments above. 

The warning message itself includes the string of the units. Would it be possible to just return that string at least instead of returning `None`? That would at least allow us to work around the issue and use astropy's tools to ingest that string and convert back to a unit object. 

But I remain convinced that the best strategy here should be to allow users to put any units they want in a `map` and only once they go to save this to disk as a FITS file does this issue an error saying that it can't be done. So instead of getting
```
WARNING: SunpyMetadataWarning: Could not parse unit string "electron / pix2" as a valid FITS unit.
See https://docs.sunpy.org/en/stable/how_to/fix_map_metadata.html for how to fix metadata before loading it with sunpy.map.Map.
See https://fits.gsfc.nasa.gov/fits_standard.html for the FITS unit standards. [sunpy.map.mapbase]
``` 
when doing a `map.unit` in memory, users would get: 
```
ERROR: SunpyMetadataError: Could not parse unit string "electron / pix2" as a valid FITS unit.
See https://docs.sunpy.org/en/stable/how_to/fix_map_metadata.html for how to fix metadata before loading it with sunpy.map.Map.
See https://fits.gsfc.nasa.gov/fits_standard.html for the FITS unit standards. [sunpy.map.mapbase]
```
when doing a `map.save('filename.fits')`.

**Comment by Cadair** [comment]
In theory I think I'd be ok with only erroring on save to fits, as if you save to asdf it wouldn't have to error.

I think that it would be a very new code path for us though, we currently maintain a FITS header as the source of truth for all the metadata, so when we save it to disk we just save it. Changing that to be more flexible would be both a technical and philosophical shift in implementation.

We are currently in the process of rewriting the guts of map (#7547) so this might be something which might be a little easier to do after that work is complete.

**Comment by starfleetjames** [comment]
Okay that makes sense. I can imagine the lift could get quite heavy if doing this switch because then you'd either have to have a lot of converters to trim all the allowed flexibility back down to FITS header standard in the process of saving, and/or end up issuing a warning/error for every instance where the flexibility expanded beyond the standard. 
This has now got me thinking upstream though. How hard is it for updates to be made to FITS itself?
