### ISSUE TITLE
Fix this specific improper comparison between quantities and strings 

### ISSUE THREAD

**Issue by GillySpace27** [sunpy/sunpy#7839]
### Describe the bug

When I was trying to construct a new Fido Client, I ran into an issue where there was a comparison happening that threw exceptions. In the else clause of the following method, you can see the original and my hotfix. 

In sunpy.net.attr.Range:

>  Around line 470
    def __contains__(self, other):
        if isinstance(other, Range):
            return self.min <= other.min and self.max >= other.max
        else:
            return self.min <= other <= self.max
            # return self.min.value <= int(other) <= self.max.value #TODO Fix Hotfix

I believe that it was happening when I was trying to get the client to understand my a.Wavelength. Removing that attr from the query fixes the exception and also returns an result with all wavelengths included, which makes sense. But leaving it in causes the error.

### To Reproduce

    from sunpy.net import Fido
    from sunpy.net import attrs as a
    import astropy.units as u

    # Example usage
    time_range = a.Time("2023-10-11 00:00:00", "2023-10-11 01:00:00")
    instrument = a.Instrument("AIASynoptic")
    wavelength = a.Wavelength(193 * u.angstrom)
    sample = a.Sample(10 * u.minute)
    results = Fido.search(time_range, instrument, wavelength)  # , sample)  # , wavelength)

    print(results)

    Fido.fetch(results, path="DLData/{file}")

Here's the error:

>File "/Users/cgilbert/vscode/sunpy/sunpy/.venv/lib/python3.12/site-packages/astropy/units/quantity_helper/converters.py", line 196, in converters_and_unit
    if can_have_arbitrary_unit(args[i]):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cgilbert/vscode/sunpy/sunpy/.venv/lib/python3.12/site-packages/astropy/units/quantity_helper/converters.py", line 138, in can_have_arbitrary_unit
    return np.all(np.logical_or(np.equal(value, 0.0), ~np.isfinite(value)))
                                ^^^^^^^^^^^^^^^^^^^^
numpy._core._exceptions._UFuncNoLoopError: ufunc 'equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes._PyFloatDType'>) -> None

> During handling of the above exception, another exception occurred:

>Traceback (most recent call last):
  File "/Users/cgilbert/vscode/sunpy/sunpy/net/dataretriever/sources/aia_synoptic.py", line 92, in <module>
    results = Fido.search(time_range, instrument, wavelength)  # , sample)  # , wavelength)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cgilbert/vscode/sunpy/sunpy/net/fido_factory.py", line 314, in search
    results = query_walker.create(query, self)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cgilbert/vscode/sunpy/sunpy/net/attr.py", line 635, in create
    return self.createmm(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cgilbert/vscode/sunpy/sunpy/util/functools.py", line 17, in wrapper
    return dispatcher.dispatch(args[1].__class__)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cgilbert/vscode/sunpy/sunpy/net/fido_factory.py", line 243, in _create_and
    return factory._make_query_to_client(*query.attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cgilbert/vscode/sunpy/sunpy/net/fido_factory.py", line 481, in _make_query_to_client
    results.append(tmpclient.search(*query))
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cgilbert/vscode/sunpy/sunpy/net/dataretriever/client.py", line 245, in search
    filesmeta = scraper._extract_files_meta(tr, extractor=pattern, matcher=matchdict)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cgilbert/vscode/sunpy/sunpy/net/scraper.py", line 462, in _extract_files_meta
    if k in matcher and str(metadict[k]) not in matcher[k]:
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cgilbert/vscode/sunpy/sunpy/net/attr.py", line 471, in __contains__
    return self.min <= other <= self.max
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cgilbert/vscode/sunpy/sunpy/.venv/lib/python3.12/site-packages/astropy/units/quantity.py", line 696, in __array_ufunc__
    raise e
  File "/Users/cgilbert/vscode/sunpy/sunpy/.venv/lib/python3.12/site-packages/astropy/units/quantity.py", line 641, in __array_ufunc__
    converters, unit = converters_and_unit(function, method, *inputs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cgilbert/vscode/sunpy/sunpy/.venv/lib/python3.12/site-packages/astropy/units/quantity_helper/converters.py", line 207, in converters_and_unit
    raise TypeError(
TypeError: Unsupported operand type(s) for ufunc less_equal: 'Quantity,str'

### System Details

==============================
sunpy Installation Information
==============================

General
#######
OS: Mac OS 14.5
Arch: 64bit, (arm)
sunpy: 6.0.dev586+gfbe4c87a8.d20241016
Installation path: /Users/cgilbert/vscode/sunpy/sunpy/.venv/lib/python3.12/site-packages/sunpy-6.0.dev586+gfbe4c87a8.d20241016.dist-info

Required Dependencies
#####################
astropy: 6.1.4
numpy: 2.1.2
packaging: 24.1
parfive: 2.1.0
pyerfa: 2.0.1.4
requests: 2.32.3

Optional Dependencies
#####################
sunpy: 6.0.dev586+gfbe4c87a8.d20241016

### Installation method

pip

**Comment by wtbarnes** [comment]
Are you able to reproduce this behavior without your new client?

**Comment by parharti** [comment]
Hey @wtbarnes,

I gave it a shot without using the new client, and I didn’t run into any issues with the wavelength it seems to work fine with the VSOClient. I’m thinking the error could’ve been related to how the custom client was set up, or maybe it’s something that’s been addressed already in a newer version of sunpy.net.

When I tried running the same code from the "reproduced" section, everything worked as expected, and I didn’t see any problems with wavelength being treated as a string.

Honestly, I’m still not sure exactly what went wrong or how to fix it, but this whole process has been a great learning experience. It’s been super helpful to explore into SunPy and how its clients work, especially in terms of building custom ones.
