### ISSUE TITLE
sunpy.data.manager.get  throws an error if attempting to redownload a file which has been deleted

### ISSUE THREAD

**Issue by Sauravroy34** [sunpy/sunpy#7949]
### Describe the bug

There might be a good chance that  after downloading the file using data_manger .get() someone might accidentally delete it 
so the file stays in the database but is not present in the directory 

 https://github.com/sunpy/sunpy/blob/main/sunpy/data/data_manager/manager.py#L87-L97
when attempting to re-download it 
 and so line 97  (``` hash_file(details['file_path']) ``` throws error  since file has been deleted 

### To Reproduce

```
from sunpy.data import manager
import os 
@manager.require('test_file',
                 ['http://data.sunpy.org/sample-data/predicted-sunspot-radio-flux.txt'],
                 '4c85b04a5528aa97eb84a087450eda0421c71833820576330bba148564089b11')
def test2_function():
    return manager.get('test_file')

test2_function()

# file deleted 
os.remove("~/sunpy/data_manager/predicted-sunspot-radio-flux.txt")

test2_function()
```

### Screenshots

Traceback (most recent call last):
  File "/home/saurav/Desktop/test.py", line 13, in <module>
    test2_function()
  File "/home/saurav/Desktop/sunp_env/sunpy/sunpy/data/data_manager/manager.py", line 62, in wrapper
    self._download_and_cache_file(name, urls, sha_hash)
  File "/home/saurav/Desktop/sunp_env/sunpy/sunpy/data/data_manager/manager.py", line 98, in _download_and_cache_file
    if hash_file(details['file_path']) != details['file_hash']:
  File "/home/saurav/Desktop/sunp_env/sunpy/sunpy/util/util.py", line 197, in hash_file
    with open(path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/saurav/sunpy/data_manager/predicted-sunspot-radio-flux.txt'

**Comment by Sauravroy34** [comment]
shall we re-download it? or throw a custom warning/error?

**Comment by nabobalis** [comment]
I feel like it should redownload it with a warning message.

**Comment by Sauravroy34** [comment]
Sure will have pr soon
