### ISSUE TITLE
tox does not work with Python 3

### ISSUE THREAD

**Issue by derdon** [sunpy/sunpy#976]
Calling ``tox -e py33`` fails with the following output (tl;dr: problematic part: ``from itertools import izip, imap, count``):

```pytb
tox -e py33               
GLOB sdist-make: /home/derdon/repos/python/3rdparty/sunpy/setup.py
py33 create: /home/derdon/repos/python/3rdparty/sunpy/.tox/py33
py33 installdeps: pytest, numpy, beautifulsoup4, suds-jurko, sqlalchemy
py33 inst: /home/derdon/repos/python/3rdparty/sunpy/.tox/dist/sunpy-0.4.0.zip
py33 runtests: PYTHONHASHSEED='3798333599'
py33 runtests: commands[0] | pip install pytest-cov
Downloading/unpacking pytest-cov
  Downloading pytest-cov-1.6.tar.gz
  Running setup.py (path:/home/derdon/repos/python/3rdparty/sunpy/.tox/py33/build/pytest-cov/setup.py) egg_info for package pytest-cov
    
Requirement already satisfied (use --upgrade to upgrade): pytest>=2.2.3 in ./.tox/py33/lib/python3.3/site-packages (from pytest-cov)
Downloading/unpacking cov-core>=1.6 (from pytest-cov)
  Downloading cov-core-1.12.tar.gz
  Running setup.py (path:/home/derdon/repos/python/3rdparty/sunpy/.tox/py33/build/cov-core/setup.py) egg_info for package cov-core
    
Requirement already satisfied (use --upgrade to upgrade): py>=1.4.20 in ./.tox/py33/lib/python3.3/site-packages (from pytest>=2.2.3->pytest-cov)
Downloading/unpacking coverage>=3.4 (from cov-core>=1.6->pytest-cov)
  Downloading coverage-3.7.1.tar.gz (284kB): 284kB downloaded
  Running setup.py (path:/home/derdon/repos/python/3rdparty/sunpy/.tox/py33/build/coverage/setup.py) egg_info for package coverage
    
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
Installing collected packages: pytest-cov, cov-core, coverage
  Running setup.py install for pytest-cov
    
  Running setup.py install for cov-core
    
    
    Wrote pth file for subprocess measurement to /home/derdon/repos/python/3rdparty/sunpy/.tox/py33/lib/python3.3/site-packages/init_cov_core.pth
  Running setup.py install for coverage
    building 'coverage.tracer' extension
    x86_64-pc-linux-gnu-gcc -pthread -fPIC -I/usr/include/python3.3 -c coverage/tracer.c -o build/temp.linux-x86_64-3.3/coverage/tracer.o
    x86_64-pc-linux-gnu-gcc -pthread -shared build/temp.linux-x86_64-3.3/coverage/tracer.o -L/usr/lib64 -lpython3.3 -o build/lib.linux-x86_64-3.3/coverage/tracer.cpython-33.so
    
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    Installing coverage-3.3 script to /home/derdon/repos/python/3rdparty/sunpy/.tox/py33/bin
    Installing coverage script to /home/derdon/repos/python/3rdparty/sunpy/.tox/py33/bin
    Installing coverage3 script to /home/derdon/repos/python/3rdparty/sunpy/.tox/py33/bin
Successfully installed pytest-cov cov-core coverage
Cleaning up...
py33 runtests: commands[1] | pip install scipy
Requirement already satisfied (use --upgrade to upgrade): scipy in ./.tox/py33/lib/python3.3/site-packages
Cleaning up...
py33 runtests: commands[2] | pip install matplotlib
Requirement already satisfied (use --upgrade to upgrade): matplotlib in ./.tox/py33/lib/python3.3/site-packages
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.5 in ./.tox/py33/lib/python3.3/site-packages (from matplotlib)
Requirement already satisfied (use --upgrade to upgrade): python-dateutil!=2.1 in ./.tox/py33/lib/python3.3/site-packages (from matplotlib)
Requirement already satisfied (use --upgrade to upgrade): tornado in ./.tox/py33/lib/python3.3/site-packages (from matplotlib)
Requirement already satisfied (use --upgrade to upgrade): pyparsing>=1.5.6,!=2.0.0 in ./.tox/py33/lib/python3.3/site-packages (from matplotlib)
Requirement already satisfied (use --upgrade to upgrade): nose in ./.tox/py33/lib/python3.3/site-packages (from matplotlib)
Requirement already satisfied (use --upgrade to upgrade): six in ./.tox/py33/lib/python3.3/site-packages (from python-dateutil!=2.1->matplotlib)
Cleaning up...
py33 runtests: commands[3] | pip install astropy
Requirement already satisfied (use --upgrade to upgrade): astropy in ./.tox/py33/lib/python3.3/site-packages
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.5.0 in ./.tox/py33/lib/python3.3/site-packages (from astropy)
Cleaning up...
py33 runtests: commands[4] | pip install pandas
Requirement already satisfied (use --upgrade to upgrade): pandas in ./.tox/py33/lib/python3.3/site-packages
Requirement already satisfied (use --upgrade to upgrade): python-dateutil>=2 in ./.tox/py33/lib/python3.3/site-packages (from pandas)
Requirement already satisfied (use --upgrade to upgrade): pytz>=2011k in ./.tox/py33/lib/python3.3/site-packages (from pandas)
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.7.0b2 in ./.tox/py33/lib/python3.3/site-packages (from pandas)
Requirement already satisfied (use --upgrade to upgrade): six in ./.tox/py33/lib/python3.3/site-packages (from python-dateutil>=2->pandas)
Cleaning up...
py33 runtests: commands[5] | pip install sqlalchemy
Requirement already satisfied (use --upgrade to upgrade): sqlalchemy in ./.tox/py33/lib/python3.3/site-packages
Cleaning up...
py33 runtests: commands[6] | python setup.py develop
running develop
running build_py
creating build/lib.linux-x86_64-3.3
error: could not create 'build/lib.linux-x86_64-3.3': Permission denied
ERROR: InvocationError: '/home/derdon/repos/python/3rdparty/sunpy/.tox/py33/bin/python setup.py develop'
py33 runtests: commands[7] | py.test --cov-report html --cov sunpy --junitxml=result.xml --pyargs sunpy.tests
Traceback (most recent call last):
  File "/home/derdon/repos/python/3rdparty/sunpy/.tox/py33/lib/python3.3/site-packages/_pytest/config.py", line 502, in getconftestmodules
    clist = self._path2confmods[path]
KeyError: local('/home/derdon/repos/python/3rdparty/sunpy/sunpy/tests')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/derdon/repos/python/3rdparty/sunpy/.tox/py33/lib/python3.3/site-packages/_pytest/config.py", line 533, in importconftest
    return self._conftestpath2mod[conftestpath]
KeyError: local('/home/derdon/repos/python/3rdparty/sunpy/sunpy/tests/conftest.py')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".tox/py33/bin/py.test", line 9, in <module>
    load_entry_point('pytest==2.5.2', 'console_scripts', 'py.test')()
  File "/home/derdon/repos/python/3rdparty/sunpy/.tox/py33/lib/python3.3/site-packages/_pytest/config.py", line 19, in main
    config = _prepareconfig(args, plugins)
  File "/home/derdon/repos/python/3rdparty/sunpy/.tox/py33/lib/python3.3/site-packages/_pytest/config.py", line 63, in _prepareconfig
    pluginmanager=pluginmanager, args=args)
  File "/home/derdon/repos/python/3rdparty/sunpy/.tox/py33/lib/python3.3/site-packages/_pytest/core.py", line 377, in __call__
    return self._docall(methods, kwargs)
  File "/home/derdon/repos/python/3rdparty/sunpy/.tox/py33/lib/python3.3/site-packages/_pytest/core.py", line 388, in _docall
    res = mc.execute()
  File "/home/derdon/repos/python/3rdparty/sunpy/.tox/py33/lib/python3.3/site-packages/_pytest/core.py", line 289, in execute
    res = method(**kwargs)
  File "/home/derdon/repos/python/3rdparty/sunpy/.tox/py33/lib/python3.3/site-packages/_pytest/helpconfig.py", line 27, in pytest_cmdline_parse
    config = __multicall__.execute()
  File "/home/derdon/repos/python/3rdparty/sunpy/.tox/py33/lib/python3.3/site-packages/_pytest/core.py", line 289, in execute
    res = method(**kwargs)
  File "/home/derdon/repos/python/3rdparty/sunpy/.tox/py33/lib/python3.3/site-packages/_pytest/config.py", line 618, in pytest_cmdline_parse
    self.parse(args)
  File "/home/derdon/repos/python/3rdparty/sunpy/.tox/py33/lib/python3.3/site-packages/_pytest/config.py", line 711, in parse
    self._preparse(args)
  File "/home/derdon/repos/python/3rdparty/sunpy/.tox/py33/lib/python3.3/site-packages/_pytest/config.py", line 691, in _preparse
    args=args, parser=self._parser)
  File "/home/derdon/repos/python/3rdparty/sunpy/.tox/py33/lib/python3.3/site-packages/_pytest/core.py", line 377, in __call__
    return self._docall(methods, kwargs)
  File "/home/derdon/repos/python/3rdparty/sunpy/.tox/py33/lib/python3.3/site-packages/_pytest/core.py", line 388, in _docall
    res = mc.execute()
  File "/home/derdon/repos/python/3rdparty/sunpy/.tox/py33/lib/python3.3/site-packages/_pytest/core.py", line 289, in execute
    res = method(**kwargs)
  File "/home/derdon/repos/python/3rdparty/sunpy/.tox/py33/lib/python3.3/site-packages/_pytest/capture.py", line 83, in pytest_load_initial_conftests
    return __multicall__.execute()
  File "/home/derdon/repos/python/3rdparty/sunpy/.tox/py33/lib/python3.3/site-packages/_pytest/core.py", line 289, in execute
    res = method(**kwargs)
  File "/home/derdon/repos/python/3rdparty/sunpy/.tox/py33/lib/python3.3/site-packages/_pytest/config.py", line 674, in pytest_load_initial_conftests
    self._conftest.setinitial(args)
  File "/home/derdon/repos/python/3rdparty/sunpy/.tox/py33/lib/python3.3/site-packages/_pytest/config.py", line 487, in setinitial
    self._try_load_conftest(anchor)
  File "/home/derdon/repos/python/3rdparty/sunpy/.tox/py33/lib/python3.3/site-packages/_pytest/config.py", line 498, in _try_load_conftest
    self.getconftestmodules(x)
  File "/home/derdon/repos/python/3rdparty/sunpy/.tox/py33/lib/python3.3/site-packages/_pytest/config.py", line 512, in getconftestmodules
    clist.append(self.importconftest(conftestpath))
  File "/home/derdon/repos/python/3rdparty/sunpy/.tox/py33/lib/python3.3/site-packages/_pytest/config.py", line 538, in importconftest
    self._conftestpath2mod[conftestpath] = mod = conftestpath.pyimport()
  File "/home/derdon/repos/python/3rdparty/sunpy/.tox/py33/lib/python3.3/site-packages/py/_path/local.py", line 608, in pyimport
    __import__(pkgpath.basename)
  File "/home/derdon/repos/python/3rdparty/sunpy/sunpy/__init__.py", line 23, in <module>
    from sunpy.util.config import load_config, print_config
  File "/home/derdon/repos/python/3rdparty/sunpy/sunpy/util/__init__.py", line 4, in <module>
    from sunpy.util.util import *
  File "/home/derdon/repos/python/3rdparty/sunpy/sunpy/util/util.py", line 6, in <module>
    from itertools import izip, imap, count
ImportError: cannot import name izip
ERROR: InvocationError: '/home/derdon/repos/python/3rdparty/sunpy/.tox/py33/bin/py.test --cov-report html --cov sunpy --junitxml=result.xml --pyargs sunpy.tests'
______________________________________________________________ summary _______________________________________________________________
ERROR:   py33: commands failed
```

**Comment by Cadair** [comment]
I assume this is closed by #1728.
